### ISSUE TITLE
Creating IF_cond_exp fails with NEST 1.9-8558

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/PyNN#150]
When using PyNN version 0.6 with NEST version 1.9-8558, the attached script fails. Creating IF_cond_exp cell types generates the following error message:  
{{{
          -- N E S T 2 beta --
         Neural Simulation Tool
 Copyright 1995-2009 The NEST Initiative
  Version 1.9-8558 Feb 24 2010 18:53:39

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
 Website     : http://www.nest-initiative.org
 Mailing list: nest_user@nest-initiative.org

Type 'nest.help()' to find out more about NEST.
/usr/local/lib/python2.6/dist-packages/pyNN/random.py:25: UserWarning:
GSL random number generators not available
 warnings.warn("GSL random number generators not available")

 Traceback (most recent call last):
 File "failing.py", line 28, in <module>
   cells_exc = pynn.create(pynn.IF_cond_exp, if_cond_exp_params, n=numCellsExc)
 File "/usr/local/lib/python2.6/dist-packages/pyNN/common.py", line 655, in create
   all_cells, mask_local, first_id, last_id = simulator.create_cells(cellclass, cellparams, n)
 File "/usr/local/lib/python2.6/dist-packages/pyNN/nest/simulator.py", line 161, in create_cells
   raise common.InvalidModelError(errmsg)
pyNN.common.InvalidModelError: UnknownModelName in Create_l_i:
/iaf_cond_exp is not a known model name.
}}}
The failing script is identical to the one attached to Ticket #158.

---
### Imported from Trac ticket:159

**Opened**: 2010-02-25 11:36:15
**Last modified**: 2010-03-02 10:46:41
**Component**: nest
**Priority**: major
**Owner**: apdavison
**Reporter**: bruederle

**Comment by Haffi112** [comment]
I had this problem and only discovered it by googling around. It would at least be nice if this was part of the install check routine (my install check passed all the test even though I compiled nest without gsl).
