### ISSUE TITLE
FixedNumber(Pre|Post)Connector assign wrong weights from a weights array

### ISSUE THREAD

**Issue by sbillaudelle** [NeuralEnsemble/PyNN#255]
Supplying a FixedNumberPreConnector (or …Post…) with an array of weights their assignment is borked.

Taking a look at the following setup:
- Two populations with three neurons each.
- Every post-synaptic neuron is going to be connected with two pre-synaptic ones.
- Since we are going to see six connections being created we supply the connector with an array containing six weight values (according to the API docs).

Instead of all the values being used, the connector ends up using only the first three of them. The connection matrix looks like this:

``` python
[[ 0.1  nan  nan ]
 [ nan  0.2  0.2 ]
 [ 0.3  0.3  0.3 ]]
```

The problem lies in the connector's connect method where we randomly select the pre-synaptic neurons and let the connection manager connect them to the target. We do this for each post-synaptic neuron using the original weights array instead of discarding the first n elements.

Another issue is that we use a weight for every non-existent connection (nan), too. This is becoming obvious when using a RandomDistribution as a weights source. In this case we generate too many weights which might become a performance bottleneck for huge networks and – far more important – might alter the statistics!

Here's a minimal example for this issue:

``` python
import numpy
import pyNN.nest as pynn
pynn.setup()

size = 3

pre = pynn.Population(size, pynn.IF_curr_alpha)
post = pynn.Population(size, pynn.IF_curr_alpha)

rng = pynn.NumpyRNG(42)

conn = pynn.FixedNumberPreConnector(2, weights=numpy.array([.1, .2, .3, .4, .5, .6]))
proj = pynn.Projection(pre, post, conn)

print proj.getWeights(format='array')
```

As a final note: I tested it using the nest simulator. Interestingly the nest module has it's own implementation of the FNPreC but not the FNPostC. The issue is present in both, the reference implementation and the nest one.

**Comment by apdavison** [comment]
Closing, as we're no longer supporting the 0.7 branch
