### ISSUE TITLE
PopulationView behavior with mpirun in PyNN-0.7.5

### ISSUE THREAD

**Issue by bernhardkaplan** [NeuralEnsemble/PyNN#275]
In PyNN-0.7.5 the behaviour of PopulationView is not as intended (from my point of view) when used with mpirun, i.e. when used with mpirun the printed data (spikes or voltages) is the same for all PopulationViews - or the correct way to use it would be with print_v( .. gather=False) and then merging the different files in order to get the data from the different views.
In PyNN-0.8beta1 there seems to be a problem with write_data

Here is a script to reproduce the behavior:
https://gist.github.com/bernhardkaplan/7984438

**Comment by apdavison** [comment]
This appears to be specific to `pyNN.nest`. When run with `pyNN.neuron` the correct cells are saved to the correct files.
