### ISSUE TITLE
Request for editable/development mode support in setup.py

### ISSUE THREAD

**Issue by napratin** [NeuralEnsemble/PyNN#288]
Sometimes it is very convenient to be able to git checkout a branch of PyNN to immediately switch to using a particular version. The current repository structure makes this a little difficult.

The primary issue is that the top level package is called `src`. A development mode/editable install from a working copy (`pip install -e <path>`) simply puts an egg-link back to the repo root `PyNN`, and thus effectively *installs* `src` (which is a valid Python package, therefore `import src` now works, but all `import pyNN.*` fail).

Note that this is not a problem for regular installs because of the `'pyNN': 'src'` package mapping in [`setup.py`](https://github.com/NeuralEnsemble/PyNN/blob/master/setup.py#L44). Renaming `src` to `pyNN` should allow both types of installs (regular and development mode).

In the long run, I'd recommend switching from `distutils` to `setuputils`, which takes an explicit develop command (`python setup.py develop`). That should serve the same purpose as `pip install -e` but you get to do any additional processing in `setup.py` for development mode, if necessary (e.g. compiling NEURON models). 

PS: I was trying to do this to switch to 0.7 in order to use brian, which is not stable on the master branch. I realize that using virtualenv would solve my issue, but I still think `src` should be renamed `pyNN` just to be consistent and less confusing, unless there is a strong reason not to?

**Comment by apdavison** [comment]
Implemented in f10248b
