### ISSUE TITLE
ParameterSpace should have a method to add a new item to the schema

### ISSUE THREAD

**Issue by JoelChavas** [NeuralEnsemble/PyNN#299]
If self.schema is defined in ParameterSpace, if we want to add a new key, we can't usse in the current state the update method. Indeed, it will say that the key is not present. 
ParameterSpace should provide either a method add in which it adds a new key (corresponding to adding the key with the corresponding type to schema and then calling update with the new parameter). ANother option would be to add an attribute new_item_authorized in the update method

**Comment by apdavison** [comment]
I think it's straightforward to first add the key to `self.schema` before updating the parameterspace, so I don't think it's necessary to add a new method to `ParameterSpace` for this.
