### ISSUE TITLE
signs of inhibitory synaptic weights differ between ranks

### ISSUE THREAD

**Issue by albada** [NeuralEnsemble/PyNN#339]
Using PyNN 0.7.5 with NEST 10kproject revision 10711 in parallel simulations, getWeights and saveConnections return negative values on some ranks and positive values on others for inhibitory connections, at least using FromListConnector and conductance-based synapes (neuron model: IF_cond_exp).

The PotjansDiesmann2014 microcircuit model in the HBP repository (git@gitviz.kip.uni-heidelberg.de:hbp-sp9-benchmarks) shows this behavior when using the without_multapses connectivity option.

The behavior is correct (negative signs) when using only a single process.

**Comment by apdavison** [comment]
In fact, the correct behaviour at the PyNN level would be positive signs for conductance-based and negative signs for current-based synapses. For inhibitory, conductance-based synapses the weights are converted to negative values internally for NEST.
