### ISSUE TITLE
README.rst not included in tarball

### ISSUE THREAD

**Issue by p-muller** [NeuralEnsemble/PyNN#342]
On the INCF download page (http://software.incf.org/software/pynn/download), the archive PyNN-0.8beta2.tar.gz  (http://software.incf.org/software/pynn/pynn/pynn-0.8beta2.tar.gz/at_download/file)
does not contain the file README.rst, which is opened by setup.py. This causes the installation to fail:

```
$ mkdir /tmp/foo ; python setup.py install --prefix=/tmp/foo
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    long_description = open("README.rst").read(),
IOError: [Errno 2] No such file or directory: 'README.rst'
```

**Comment by apdavison** [comment]
Fixed MANIFEST.in and uploaded a new tarball to software.incf.org
