### ISSUE TITLE
'Population' object has no attribute '_recorder_class'

### ISSUE THREAD

**Issue by dabliss** [NeuralEnsemble/PyNN#344]
I cloned the `PyNN` repo about an hour ago, and began to work through the tutorial on the `PyNN` website.  The first call to the `Population` class (`pyNN.common.populations.Population`) raised the error below.

The relevant part of the tutorial is here: http://neuralensemble.org/docs/PyNN/neurons.html#populations.
```
In [16]: tc_cells = Population(100, thalamocortical_type)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-d586a3ace3b7> in <module>()
----> 1 tc_cells = Population(100, thalamocortical_type)

/usr/local/lib/python2.7/dist-packages/pyNN/common/populations.pyc in __init__(self, size, cellclass, cellparams, structure, initial_values, label)
    636             raise TypeError("cellclass must be an instance or subclass of BaseCellType, not a %s" % type(cellclass))
    637         self.annotations = {}
--> 638         self.recorder = self._recorder_class(self)
    639         # Build the arrays of cell ids
    640         # Cells on the local node are represented as ID objects, other cells by integers

AttributeError: 'Population' object has no attribute '_recorder_class'
```

**Comment by apdavison** [comment]
The documentation is unclear on this subject, but `common.populations.Population` is an abstract base class and should not be instantiated. Instead you should do something like:
```
from pyNN.nest import Population
```
or
```
from pyNN.neuron import Population
```
depending on which simulators you have installed.

**Comment by dabliss** [comment]
Great, thanks.  Yep, that resolved it.

**Comment by Tigeraus** [comment]
Using macOS and comes this issue:

<pre>
In [4]: from pyNN.neuron import Population
/Users/huzi/anaconda2/lib/python2.7/site-packages/pyNN/neuron/__init__.py:14: UserWarning: mpi4py not available
  warnings.warn("mpi4py not available")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-2c45e80e1123> in <module>()
----> 1 from pyNN.neuron import Population

/Users/huzi/anaconda2/lib/python2.7/site-packages/pyNN/neuron/__init__.py in <module>()
     19 from pyNN.recording import get_io
     20 from pyNN.space import Space
---> 21 from pyNN.neuron import simulator
     22 from pyNN.neuron.random import NativeRNG
     23 from pyNN.neuron.standardmodels.cells import *

/Users/huzi/anaconda2/lib/python2.7/site-packages/pyNN/neuron/simulator.py in <module>()
     30 import numpy
     31 import os.path
---> 32 from neuron import h, nrn_dll_loaded
     33 from operator import itemgetter
     34

ImportError: No module named neuron
</pre>

when I tried to install `neuron`, 

<pre>
neuron|⇒ pip install neuron
Collecting neuron
  Using cached https://mirrors.ustc.edu.cn/pypi/web/packages/69/c5/478ce27c3988568b8447351760b9332f4a836a2432d9cd68f89a5fcbcd54/NEURON-7.2.536.15.tar.gz
    Complete output from command python setup.py egg_info:
    Only Windows and 64-bit Linux currently supported by PyNEURON

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/r_/4vjk7rln2ylgspwbj7ztvx9h0000gp/T/pip-build-QaIalI/neuron/
</pre>

Is there any solution?

**Comment by apdavison** [comment]
The PyNN documentation contains instructions for installing NEURON with Python:

http://neuralensemble.org/docs/PyNN/installation.html#installing-neuron
