### ISSUE TITLE
Attempting to instantiate base classes, e.g. `common.Population` should raise an informative Exception.

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/PyNN#346]
cf #344

**Comment by swenzel** [comment]
How about prefixing the base classes with 'Base'? (e.g. 'BasePopulation')
This way it is clear that it is an abstract class.

**Comment by apdavison** [comment]
`common.Population` is an optional base class. Backends may use it to get a lot of functionality "for free", but they are not obliged to.

**Comment by apdavison** [comment]
I've added an error message if you try to instantiate one of the `common` base classes. Perhaps, though, it would be better to rename them, e.g. `CommonPopulation` (since `BasePopulation` is taken).
