### ISSUE TITLE
RandomDistribution lambda keyword (for Poisson distribution) raises SyntaxError

### ISSUE THREAD

**Issue by dabliss** [NeuralEnsemble/PyNN#347]
The `lambda` keyword for RandomDistribution (used in the specification of a Poisson distribution) raises a SyntaxError, as the Python interpreter reads `lambda` as an attempt to create a `lambda` function.

The line of code used below comes from the PyNN tutorial: http://neuralensemble.org/docs/PyNN/connections.html#convergent-fan-in-connections.
```
In [101]: distr_npre = RandomDistribution(distribution='poisson', lambda=5)
  File "<ipython-input-101-c8a46e9bc5fb>", line 1
    distr_npre = RandomDistribution(distribution='poisson', lambda=5)
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by apdavison** [comment]
Thanks for spotting this. As a workaround, you can do:
```python
RandomDistribution(distribution='poisson', **{'lambda': 5})
```

I've just submitted a pull request (#349) to rename "lambda" to "lambda_" in this context.

**Comment by apdavison** [comment]
Renamed "lambda" to "lambda_" in 9072827825951d26aa8c90b2891e5c6c698a2749
