### ISSUE TITLE
Connections cannot be sliced

### ISSUE THREAD

**Issue by dabliss** [NeuralEnsemble/PyNN#348]
The `connections` attribute of a `Projection` is a generator that iterates over all the synaptic connections in the `Projection`.  The tutorial (http://neuralensemble.org/docs/PyNN/connections.html#accessing-weights-and-delays) indicates that this generator can be sliced, as in
```
inhibitory_connections.connections[0].weight
```
or
```
for c in inhibitory_connections.connections[:5]:
    c.weight *= 2
```
However, executing this code raises a `TypeError`:
```
In [134]: inhibitory_connections.connections[0]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-134-b1388bba384d> in <module>()
----> 1 inhibitory_connections.connections[0]

TypeError: 'generator' object has no attribute '__getitem__'
```
Converting `connections` to a list causes slicing to work (as, in general, lists support slicing).
```
In [137]: list(inhibitory_connections.connections)[0].weight
Out[137]: 0.10015416351912557
```

**Comment by apdavison** [comment]
Documentation updated to reflect the change of the `Projections.connections` attribute from a list to a generator.
