### ISSUE TITLE
`SingleCompartmentNeuron` requires arguments `tau_e`, `tau_i`, `e_e`, and `e_i`, but does not use these variables

### ISSUE THREAD

**Issue by dabliss** [NeuralEnsemble/PyNN#354]
It's all in the subject line.  `SingleCompartmentNeuron` is located in `pyNN.neuron.cells`.

I'm happy to remove these required arguments and submit a pull request, if removing them seems like the right course of action.

**Comment by dabliss** [comment]
And `BaseSingleCompartmentNeuron` doesn't use its required argument `c_m`.

**Comment by apdavison** [comment]
`SingleCompartmentNeuron` and `BaseSingleCompartmentNeuron` are abstract base classes, which are not themselves instantiated, but are inherited by sub-classes. Variables such as `tau_e` are used by the sub-classes.

**Comment by dabliss** [comment]
Fair enough.  It seems to me that everything would work just as well if the base classes required only the arguments they used, and that would clarify how the variables are used in the class hierarchy -- i.e., variables would appear only where they are used.
