### ISSUE TITLE
neo 0.4.0 raises AssertionError when write_data is called during a parallel simulation

### ISSUE THREAD

**Issue by dabliss** [NeuralEnsemble/PyNN#357]
`merged.merge(block)` in `recording/__init__` fails, apparently because in `_get_current_segment` the `neo.SpikeTrain` objects are not given a `name` attribute.  All names are set to `None`, so merging, which is based on name-matching, fails.

**Comment by apdavison** [comment]
Neo 0.4.0 has not yet been released. PyNN currently requires Neo 0.3.3. Do you see the error with 0.3.3?

**Comment by dabliss** [comment]
No, just with 0.4.0.  I'm using the development version, from Neo's Git repo.

**Comment by apdavison** [comment]
Closing this, as it concerns an unsupported version of Neo.
