### ISSUE TITLE
TypeError: larray_compatible_ufunc() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by swenzel** [NeuralEnsemble/PyNN#358]
Hey there,

I've just downloaded 0.8dev in order to have up to date functionality. Noticed one issue though.
Using 'power(-d/2.0, 2)' in a distance function for a connector, I get this error.

```
Traceback (most recent call last):
  File "maas_lsm.py", line 146, in <module>
    connector = DDPC(d_func[con_type])
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/connectors.py", line 346, in __init__
    assert 0 <= self.distance_function(0)
  File "<string>", line 1, in <lambda>
TypeError: larray_compatible_ufunc() takes exactly 1 argument (2 given)
```

The reason is lazyarray, which does not (yet) support ufuncs with more than one argument.
Problematic functions are:
`arctan2, fmod, hypot, ldexp, power, maximum, minimum`
I'd suggest to import them again directly from numpy, until this is solved.

Cheers
Swen

**Comment by apdavison** [comment]
As a temporary workaround, does "(-d/2.0)**2" work?

**Comment by swenzel** [comment]
I've changed the pyNN source to use the imports from numpy, but yes I guess your solution does also work.

**Comment by apdavison** [comment]
Fixed for the most common use case (scalar second argument) in https://github.com/NeuralEnsemble/lazyarray/pull/18
Requires lazyarray>=0.5.0
