### ISSUE TITLE
AttributeError: '_State' object has no attribute 'segment_counter'

### ISSUE THREAD

**Issue by swenzel** [NeuralEnsemble/PyNN#359]
Using pyNN 0.8dev I got this error when calling Population.get_data()
```
Traceback (most recent call last):
  File "git/test/maas_lsm.py", line 172, in <module>
    print(pop.get_data().segments[0].analogsignalarrays)
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/common/populations.py", line 490, in get_data
    return self.recorder.get(variables, gather, self._record_filter, clear)
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/recording/__init__.py", line 287, in get
    data.segments.append(self._get_current_segment(filter_ids=filter_ids, variables=variables, clear=clear))
  File "/home/wenzel/.local/lib/python2.7/site-packages/pyNN/recording/__init__.py", line 234, in _get_current_segment
    segment = neo.Segment(name="segment%03d" % self._simulator.state.segment_counter,
AttributeError: '_State' object has no attribute 'segment_counter'
```
In order to solve it I've added an initialisation (to 0) for the variable `segment_counter` belonging to the class `common.control.BaseState`.
I wonder why travis did not notice this issue though, since actually you seem to have tests for it.
Reproducable with:
```
import pyNN.nest as sim
p = sim.Population(14, sim.IF_cond_alpha())
p.record('v')
sim.run(12.3)
data = p.get_data()
```

**Comment by apdavison** [comment]
The problem is that you didn't call `sim.setup()`, although it is impossible to know this from the error message. I've created a new ticket, #360, to address the error message problem.

**Comment by swenzel** [comment]
Ah, thanks. Okay, well I'd suggest to check in `run()` whether `setup()` was called before.
And maybe even do it automatically if not?
