### ISSUE TITLE
utf string error in projections.py

### ISSUE THREAD

**Issue by vilim** [NeuralEnsemble/PyNN#365]
I encountered a small bug in common/projections.py, in that python threw a string decoding error in the quoted code because of the arrow character.

in src/common/projection.py
```
     93         if label is None:
     94             if self.pre.label and self.post.label:
---> 95                 self.label = "%s→%s" % (self.pre.label, self.post.label)
     96         Projection._nProj += 1
     97 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)
```

Adding an u before "%s→%s", to make it an unicode string (u"%s→%s") removes the error in my configuration. I am running python 2.7.8. on os x / macports

**Comment by apdavison** [comment]
Fixed in 38a0351
