### ISSUE TITLE
Wrong AdEx dynamics for delta_T=0 in Neuron backend

### ISSUE THREAD

**Issue by bvogginger** [NeuralEnsemble/PyNN#367]
In the Adapative-Exponential I&F neuron ('EIF_cond_exp_isfa_ista' or 'EIF_curr_exp_isfa_ista'), the neuron dynamics are wrong in the Neuron backend when the slope factor 'delta_T' is set to 0.

NEURON triggers a spike when "v_spike" is reached. But, the membrane voltage should go to infinity as soon as "v_thresh" is reached.
See http://www.scholarpedia.org/article/Adaptive_exponential_integrate-and-fire_model#Physiological_interpretation, where the limit delta_T -> 0 is discussed.

The term: g_L * delta_T *exp((V-v_thresh)/delta_T) for limes delta_T -> 0 goes to 0 when V < v_thresh, and towards infinity when V>v_thresh. Hence, v_thresh is virtual spike detection threshold.
See: [wolframalpha] (http://www.wolframalpha.com/input/?i=limes+x-%3E0+x*exp%281%2Fx%29)

In contrast, Nest handles this case correctly.
![adex_delta_t_zero](https://cloud.githubusercontent.com/assets/1301537/8430783/6e6a5e8e-1f34-11e5-9635-abaeb200e7b9.png)

Versions used:
pyNN: 0.7.6dev
Nest: 2.2.2
Neuron: 7.2

I can provide the script to generate the plot.

**Comment by apdavison** [comment]
Fixed in master (15636c8) and in 0.7 (a86c86e)
