### ISSUE TITLE
pynn 0.8 not available via pip install

### ISSUE THREAD

**Issue by bvogginger** [NeuralEnsemble/PyNN#375]
The documentation of pyNN 0.8 proposes to install pyNN via:
> pip install pyNN

Unfortunately, pyNN 0.8 is not available on pypi.
When this is fixed, please also update the install line to include the version.
> pip install pyNN==0.8.0

**Comment by bvogginger** [comment]
Note that this is really confusing, because "pip install pyNN" installs pyNN 0.7.5.
When you then try to run pyNN 0.8 examples, this won't work!

**Comment by apdavison** [comment]
PyNN 0.8.0 is now available on PyPI
