### ISSUE TITLE
Add warning that NEURON 7.4 doesn't work with PyNN 0.8 

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#382]
There is some [info online](http://www.neuron.yale.edu/phpBB/viewtopic.php?f=2&t=3377) regarding this, but it would be useful if there was a warning printed if the latest PyNN is used with the standard release of NEURON 7.4, until the problem is resolved.

Maybe check for supported version with a call to `neuron.h.nrnversion()`?

**Comment by apdavison** [comment]
Michael Hines has now updated the standard distribution files, so the problem should be resolved.
