### ISSUE TITLE
FixedTotalNumberConnect not found 

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#384]
I'm trying to run the example in https://github.com/NeuralEnsemble/PyNN/tree/master/examples/Potjans2014, but it requires [FixedTotalNumberConnect](https://github.com/NeuralEnsemble/PyNN/blob/master/examples/Potjans2014/network.py#L7). 

This doesn't seem to be in PyNN 0.8 though?

**Comment by pgleeson** [comment]
@apdavison we spoke about this issue briefly in Manchester. Could you remind me here on the status of this? Was it just that it wasn't implemented yet in Nest/Neuron?

**Comment by apdavison** [comment]
Can you try again? I've just updated the master branch to make this available. There are no tests for it yet, though.

**Comment by pgleeson** [comment]
Not quite yet, there's an error "global name 'source_mask' is not defined" when it reaches here: https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/connectors.py#L1008. The other connection typoes seem to have been updated with build_source_masks() methods..?

Also, minor typo here: https://github.com/NeuralEnsemble/PyNN/blob/master/examples/Potjans2014/network.py#L103

**Comment by pgleeson** [comment]
@apdavison I can have a look a updating this. Is there any reason the implementation here: https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/connectors.py#L975 should explicitly try to balance numbers of connections between nodes, as opposed to just generating a connection map independent of distribution and calling:

    self._connect_with_map(projection, connection_map)

**Comment by neworderofjamie** [comment]
Any progress on this @apdavison - I've more or less got a PyNN 0.8 backend for SpiNNaker working and I'd love to include the microcircuit as an example in the paper I'm currently writing, but time is short!

**Comment by apdavison** [comment]
@pgleeson I guess it is for efficiency, to avoid generating the entire map on all MPI nodes, but I haven't looked closely to see if `connect_with_map()` could be used.

**Comment by apdavison** [comment]
@neworderofjamie great news on the SpiNNaker backend! I'm happy to move this up my priority list. How tight is your deadline?

**Comment by neworderofjamie** [comment]
That would be awesome! I've tried swapping the connector in question for a fixed probability connector with what SEEMS like it should be the right probabilities, but the firing rates are really high (this is testing at 0.1 scale on NEST). The deadline is approximately the next month as at that point I need to switch entirely to writing up my damn thesis :)

**Comment by apdavison** [comment]
The connector now works, and has some tests (64c1119). 

Further work is still needed: see #409

**Comment by pgleeson** [comment]
Thanks @apdavison, will try it out.

**Comment by neworderofjamie** [comment]
Awesome, thanks @apdavison
