### ISSUE TITLE
Provide SpikeSourceGamma (gamma process spike source)

### ISSUE THREAD

**Issue by Huitzilo** [NeuralEnsemble/PyNN#386]
Poisson processes are commonly used in neuronal modeling to mimic spike trains from cortical neurons. However, the Poisson process demonstrably overestimates the variability of real neuronal spike trains ([Deger et al., 2012](http://link.springer.com/article/10.1007%2Fs10827-011-0362-8)). 

A gamma process of some integer order higher than 1 has been shown to approximate the statistics of real neuronal spike trains much better than the Poisson process. Therefore, it is suggested to include a SpikeSourceGamma in the standard library. Nest already provides this in the model "[gamma_sup_generator](https://github.com/nest/nest-simulator/blob/master/models/gamma_sup_generator.h)". Algorithms are described in Deger et al. (2012), with additional implementation details provided in a [Poster]http://f1000research.com/posters/1092564#) shown at Neuroinformatics 2012.
### Reference

Moritz Deger et al, “Statistical properties of superimposed stationary spike trains”, J Comput Neurosci 2012. (http://link.springer.com/article/10.1007%2Fs10827-011-0362-8)

**Comment by apdavison** [comment]
Implemented in #430
