### ISSUE TITLE
Allow an indication that recording might be done early on in the specification

### ISSUE THREAD

**Issue by rowleya** [NeuralEnsemble/PyNN#391]
This has arisen as an issue on SpiNNaker when supporting recording in conjunction with multiple calls to run e.g. in the following outline:

```
1. p.setup(...)
2. pop = p.Population(...)
...
3. run(...)
4. pop.record('spikes')
5. run(...)
...
6. p.end()
```

On SpiNNaker, we allocate resources on the machine at the first call to run().  If record has not been called on a population at this point, no space is reserved for recorded data.  Now when record is called on line 4 above, there might not be enough space local to the population for the recording to take place.  One idea might be to reserve some space "just in case", but this might mean that a network that is not to be recorded might not fit within the resources that it otherwise would have.

A couple of ideas:

1. Add a parameter to setup to indicate that recording is going to happen.  If this is set true, we will reserve space even if record has not yet been called.  Buffering will then be used where necessary if the space reserved is not big enough for all the data (or an error will be thrown if buffering is disabled).

1. Allow the specification of a schedule for the recordings e.g. ```record(schedule=[(start1, stop1), (start2, stop2), ...])```.  This has the advantage that you know up front all the space that is ever going to be required for recording.  It has the disadvantage that you might want to change this between calls to run, which would now not be possible.  It also doesn't necessarily coincide with run calls i.e. stop1 - start1 might be greater than than the runtime of the first call to run, so space would be wasted.

1. Allow the specification of the longest time over which recording might take place.  This might be specified as something like ```pop.set_maximum_recording_time('spikes', 10000)```, which would indicate that spikes will only ever need to be recorded for a maximum of 10000ms.  This again has the disadvantage of not knowing if run is ever going to be called for this amount of time.

**Comment by apdavison** [comment]
I like the idea of a recording schedule, and I've added a ticket (#408) for this proposed enhancement, but for the moment the problem behind this ticket seems to be specific to SpiNNaker, so probably should be solved by a SpyNNaker-specific argument to `setup()`.

I suggest combining your ideas 1 and 3, by adding an optional "max_recording_time" argument to `setup()`.

**Comment by rowleya** [comment]
We have now overcome this using a mechanism which allows the overall run to be done in stages, so if the first run is shorter than the second, it will run the second run in two or more sections.

We have an implementation of the recording schedule in addition to this.
