### ISSUE TITLE
Documentation: Dead links in installation instruction for NEST

### ISSUE THREAD

**Issue by bvogginger** [NeuralEnsemble/PyNN#398]
There are two dead links in the installation instructions for NEST:
http://neuralensemble.org/docs/PyNN/installation.html#installing-nest-and-pynest

**Comment by jougs** [comment]
@apdavison: The correct links for the new hompage are the following:
```
http://www.nest-simulator.org/index.php/Software:Download
    -> http://www.nest-simulator.org/download/
http://www.nest-simulator.org/index.php/Installation
    -> http://www.nest-simulator.org/installation/
```

**Comment by apdavison** [comment]
@jougs @bvogginger thanks for pointing this out.

(although @jougs  - you have read http://www.w3.org/Provider/Style/URI.html ? :-) Couldn't you add redirects so the old links still work?)

**Comment by jougs** [comment]
@apdavison: nice link. But quoting them:
> Do you really feel that the old URIs cannot be kept running? If so, you chose them very badly. Think of your new ones so that you will be able to keep then running after the next redesign.

Yes, they were chosen very badly and we like the new ones much better and will keep them for good.
