### ISSUE TITLE
NEST: Assertion `offset >= 0.0' fails for certain spike time

### ISSUE THREAD

**Issue by bvogginger** [NeuralEnsemble/PyNN#399]
Code:

    import pyNN.nest as sim
    sim.setup(spike_precision='on_grid',timestep=0.1)
    exc_stim = sim.Population(1, sim.SpikeSourceArray, cellparams={'spike_times': [353538.4]})

Error:

    python: ../../nest-2.10.0/models/spike_generator.cpp:147: void nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_(double, const nest::Time&, const nest::Time&): Assertion `offset >= 0.0' failed.

This also happens for `spike_precision='off_grid'`.

I used: Nest 2.10 and PyNN 0.8 installed via pip.

**Comment by apdavison** [comment]
This is a problem in NEST, which has been fixed in https://github.com/nest/nest-simulator/pull/327

I guess the fix will appear in NEST 3.0.
