### ISSUE TITLE
NESTSynapseMixin._get_nest_synapse_model looks for non-existent static_synapse_lbl

### ISSUE THREAD

**Issue by neworderofjamie** [NeuralEnsemble/PyNN#401]
This seems to be related to 70a2c0c6087aabf23a075853f3028b8f02ded75b when this method stopped copying synapse types for every projection, but it doesn't LOOK like 'static_synapse' is being copied ANYWHERE to create 'static_synapse_lbl' which this method is now trying to ``SetDefaults`` on.

**Comment by apdavison** [comment]
Which version of NEST are you using?

The '_lbl' feature is new in NEST 2.10, and was introduced specifically for PyNN - see https://github.com/nest/nest-simulator/pull/158 and https://github.com/nest/nest-simulator/issues/121 - in response to #377
