### ISSUE TITLE
Nest 2.10 min_delay, max_delay

### ISSUE THREAD

**Issue by uahic** [NeuralEnsemble/PyNN#403]
Using the most recent pyNN version (from git) I encounter the following issues:

`import pyNN.nest as sim
sim.setup()`

`pop1 = sim.Population(1, sim.ACSource())`
which works fine with nest 2.6.0 but gives in nest 2.10
`
     80         kernel_delay = nest.GetKernelStatus('min_delay')
---> 81         syn_delay = nest.GetDefaults('static_synapse')['min_delay']
     82         if syn_delay == numpy.inf or syn_delay > 1e300:
     83             return kernel_delay

KeyError: 'min_delay'
`
Examining the defaults of nest 2.10 reveals that there is no min_delay, possibly they removed it permanently. 

Setting the min_delay in setup(min_delay=0.1, max_delay=10.0, timestep=0.01) does not work either

`NESTError: DictError in SetDefaults_l_D: Unused dictionary items:  min_delay max_delay
`

Specifying it in a synapse 
`pop1 = sim.Population(1, sim.ACSource(), sim.StaticSynapse(min_delay=0.1))` 

did not work

**Comment by apdavison** [comment]
At present it is not possible to create populations of current sources, i.e., the code should be:
```python
pop1 = sim.ACSource()
```
not
```python
pop1 = sim.Population(1, sim.ACSource())
```
If you want multiple current sources (e.g. one per neuron in a population), you have to create a list. I've created a new ticket (#407) proposing a current source array class which would behave more like a population.
