### ISSUE TITLE
Success of population.set depends on order on NEST

### ISSUE THREAD

**Issue by astoeckel** [NeuralEnsemble/PyNN#412]
Consider the following code:

```python
import pyNN.nest as sim

pop = sim.Population(10, sim.IF_cond_exp, {})

pop.set(v_thresh=-65.0)
pop.set(v_reset=-75.0)
```

This code crashes with the following exception:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    pop.set(v_thresh=-65.0)
  File "/home/andreas/venvs/nest/lib/python2.7/site-packages/pyNN/common/populations.py", line 351, in set
    self._set_parameters(parameter_space)
  File "/home/andreas/venvs/nest/lib/python2.7/site-packages/pyNN/nest/populations.py", line 37, in _set_parameters
    nest.SetStatus(ids, param_dict)
  File "/home/andreas/venvs/nest/lib/python2.7/site-packages/nest/lib/hl_api_helper.py", line 138, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/andreas/venvs/nest/lib/python2.7/site-packages/nest/lib/hl_api_info.py", line 171, in SetStatus
    sr('Transpose { arrayload pop SetStatus } forall')
  File "/home/andreas/venvs/nest/lib/python2.7/site-packages/nest/__init__.py", line 79, in catching_sli_run
    raise _kernel.NESTError("{0} in {1}{2}".format(errorname, commandname, message))
pynestkernel.NESTError: BadProperty in SetStatus_id: Setting status of a 'iaf_cond_exp' with GID 3: Reset potential must be smaller than threshold.
```

However, executing the set commands in the opposite order works:

```python
import pyNN.nest as sim

pop = sim.Population(10, sim.IF_cond_exp, {})

pop.set(v_reset=-75.0)
pop.set(v_thresh=-65.0)
```

This is a problem since the code calling `set` would require knowledge about the neuron model to determine the correct call order ‒ and especially, from a theoretical point of view, determining the correct call order might be a hard constraint problem.

Please validate the neuron parameters just before the network is executed and not while it is still being assembled, or alternatively, assure this behaviour is consistent across all platforms. Atomically calling `pop.set` with all parameters at once is not feasible under some circumstances (and e.g. not supported by PyHMF).

Tested with PyNN version 0.8.0 and NEST version 2.10.0

**Comment by jougs** [comment]
There is no general solution to the problem of setting interdependent parameters in multiple calls.

The way we solve this problem in NEST is to set all variables in  a single call. Internally, `SetStatus` will take care that everything is done in the right order. Can you also do this in PyNN? I.e. would the following work?
```python
pop.set(v_reset=-75.0, v_thresh=-65.0)
```

**Comment by apdavison** [comment]
@astoeckel To me, this is expected and desirable behaviour. If you're setting up the network in an invalid state, the script should fail as early as possible, rather than waste time running the code in between the invalid call and the first `run()`.

@jougs yes. In PyNN 0.8 you can set all variables in a single call using the syntax you suggest. In PyNN 0.7 you pass in a dictionary.

@astoeckel If PyHMF doesn't support setting multiple parameters in a single `set()` call then that's a PyHMF bug (cc @muffgaga @electronicvisions)
