### ISSUE TITLE
NEST: get rid of DivergentConnect and ConvergentConnect

### ISSUE THREAD

**Issue by mschmidt87** [NeuralEnsemble/PyNN#414]
With commit a767e2ece2989dd60bd9a1c6cd19000fdb6cd489, the old connection routines `DivergentConnect` and `ConvergentConnect` were removed from the NEST master. 
pyNN still relies on these routines in two files and we're working on a pull request to remove them from the pyNN master as well.
These are the files:
`nest/recording.py` and `nest/standardmodels/electrodes.py`.

We can safely move to the new connection routine in `electrodes.py`. 
In `recording.py`, however, we do not understand the two lines containing `ConvergentConnect()`, which read:
`_nest_connect = lambda device, ids: nest.ConvergentConnect()`
`_nest_connect = nest.ConvergentConnect`.

What is the function of these lines? When we comment them out, the examples we tested, run through without errors. Are these lines deprecated?

**Comment by apdavison** [comment]
> What is the function of these lines?

It looks as though they are a relic left over from some earlier refactoring, I have no memory of how or when they were used. I think you can safely delete them.
