### ISSUE TITLE
Cannot use STDP synapses with list connector

### ISSUE THREAD

**Issue by neworderofjamie** [NeuralEnsemble/PyNN#417]
``` 
File "/home/jamie/virtualenvs/nest_2_10/local/lib/python2.7/site-packages/pyNN/nest/projections.py", line 60, in __init__
    connector.connect(self)
  File "/home/jamie/virtualenvs/nest_2_10/local/lib/python2.7/site-packages/pyNN/connectors.py", line 532, in connect
    connection_parameters = deepcopy(projection.synapse_type.parameter_space)
AttributeError: 'STDPMechanism' object has no attribute 'parameter_space'
```
The list connector is trying to access ``projection.synapse_type.parameter_space`` which isn't initialized. Not sure if  superclass __init__ should be called in ``STDPMechanism.__init__`` or ``FromListConnector`` should do something different.

**Comment by apdavison** [comment]
This should now be fixed. @neworderofjamie please can you give the latest master a try?

**Comment by neworderofjamie** [comment]
This seems to work great - sorry about the delay in replying - travelling etc!
