### ISSUE TITLE
Cannot set DCSource amplitude with set

### ISSUE THREAD

**Issue by Scaatis** [NeuralEnsemble/PyNN#418]
Consider the following example:
```python
>>> import pyNN.nest as sim
>>> sim.setup(timestep=1.0, min_delay=1.0)
0
>>> a = sim.DCSource()
>>> a.set(amplitude=1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "X/.local/lib/python2.7/site-packages/pyNN/standardmodels/__init__.py", line 169, in __getattr__
    self.get_parameter_names())
pyNN.errors.NonExistentParameterError: set (valid parameters for DCSource are: amplitude, start, stop)
```
Perhaps `set` is not the correct way to change this? If so, there should probably a message or a note in the documentation. Or any documentation, as the API reference is currently empty :)
P.S.: This is using pyNN from git and NEST 2.10.0

**Comment by apdavison** [comment]
> the API reference is currently empty

whoops! I'm travelling at the moment, and can't fix it until I get back to the lab next week. You could check the available methods of the `DCSource` object using `dir(a)` in your code above.

> Perhaps set is not the correct way to change this?

The correct way is `a.set_parameters(amplitude=1.0)`.

> there should probably a message or a note in the documentation

There should be a more informative error message (cf the similar issues #380, #381)

**Comment by apdavison** [comment]
I've added a specific error message when trying to use `set()` on a current source.

**Comment by apdavison** [comment]
I've created a new issue, #419, for discussing whether we should harmonize the get/set parameters methods for all relevant PyNN objects.
