### ISSUE TITLE
PyNN differential equations?

### ISSUE THREAD

**Issue by Brayan200291** [NeuralEnsemble/PyNN#420]
I have a doubt, which  one is numerical method  used in PyNN to solve differential equations for example, to solve model IF_cond_exp.

**Comment by apdavison** [comment]
There is no one single method; it is potentially different for each PyNN implementation.

**Comment by Brayan200291** [comment]
Agree with of PyNN version, or with model of neuron?

**Comment by jougs** [comment]
@Brayan200291: PyNN is "just" a front-end to different simulators, it does not solve any equations by itself.

The way in which a particular model is solved is determined by the implementation of the model in the simulator you use. Usually, this information is available in the documentation of the simulator. Feel free to refer to the corresponding mailing lists for more details.
