### ISSUE TITLE
PDF link on main website page down

### ISSUE THREAD

**Issue by nico202** [NeuralEnsemble/PyNN#421]
Don't know if website problems have to be reported here.
However, the link to the publication [pdf](http://www.frontiersin.org/neuroinformatics/10.3389/neuro.11/011.2008/abstract) to cite, is down.
Should be changed (i think) to: http://journal.frontiersin.org/article/10.3389/neuro.11.011.2008/full
Thanks, Nicolò

edit: added the right link

**Comment by apdavison** [comment]
Hi Nicolò, thanks for the report. The link should be fixed now.
