### ISSUE TITLE
pop.get_data('v', clear=True) does not clears recorded data

### ISSUE THREAD

**Issue by acerebellum** [NeuralEnsemble/PyNN#426]
After multiple simulations runs in a loop,  the recorded data increases and the clear flag does not deletes the previously recorded data.
```python
import pyNN.nest as sim
sim.setup(timestep=0.01)
while True:
   p_in = sim.Population(2, sim.SpikeSourcePoisson(rate=rate), label="input")
   p_out = sim.Population(2, sim.EIF_cond_exp_isfa_ista(), label="AdExp neurons")
   syn = sim.StaticSynapse(weight=1)
   random = sim.FixedProbabilityConnector(p_connect=1)
   connections = sim.Projection(p_in, p_out, random, syn, receptor_type='excitatory')
   p_out.record('v')
   sim.run(20.0)
   data_out = p_out.get_data('v',clear=True)
```

**Comment by apdavison** [comment]
In your example, each time you go through the loop you create two new populations. The populations from the previous iterations are no longer accessible at the Python level, but they still exist inside NEST. This could explain the increase in the size of the data.

You need to put `sim.setup()` inside the loop if you want to delete the populations from the previous iteration.

**Comment by acerebellum** [comment]
Thanks, that solved my problem.
