### ISSUE TITLE
AssertionError using Population.set() in MPI context

### ISSUE THREAD

**Issue by kennysharma** [NeuralEnsemble/PyNN#428]
**Description**

Calling `set` on a `Population` within an MPI context can produce an `AssertionError` for some parameters, the example below uses `tau_m`, but others may be impacted.

The issue may be as simple as modifying the assertion to check against local `Population` size rather than global `Population` size, but that is just my initial assumption.

**Environment**
```
pyNN 0.8.1
NEST 2.10.0
```

**Minimal Test Case**
```python
from pyNN.nest import *

population = Population(2, IF_cond_alpha())
population.set(tau_m = 20)
```

**Execution**
```shell
mpirun -np 2 test_case.py

...

Traceback (most recent call last):
  File "test_case.py", line 4, in <module>
    population.set(tau_m = 20)
  File ".../pyNN/common/populations.py", line 353, in set
    assert parameter_space.shape == (self.size,)
AssertionError
```

**Comment by apdavison** [comment]
Fixed in #431

**Comment by kennysharma** [comment]
Apologies as I was out on holiday for the past few weeks. I tested against the latest master 3ab2e44d8e19ac1e2aedf619aafb71df1dd54ab4 (including the 139be13dbcdfe6e2af9cffeea835a33399ba301c commit referenced above) and I'm encountering a new error running the same test case above:

```
Traceback (most recent call last):
  File "test_case.py", line 4, in <module>
    population.set(tau_m = 20)
  File ".../pyNN/common/populations.py", line 348, in set
    parameter_space.expand((self.size,), self._mask_local)
  File ".../pyNN/parameters.py", line 456, in expand
    self.shape = new_shape
  File ".../pyNN/parameters.py", line 243, in _set_shape
    value.shape = shape
  File ".../lazyarray.py", line 227, in _set_shape
    raise ValueError("Lazy array has fixed shape %s, cannot be changed to %s" % (self.base_value.shape, value))
ValueError: Lazy array has fixed shape (), cannot be changed to (2,)
```

**Comment by apdavison** [comment]
Sorry, I forgot that I also had to make a change to the `lazyarray` package. Please can you update to lazyarray 0.2.9 (e.g.`pip install -U lazyarray`)?

**Comment by kennysharma** [comment]
That does indeed fix that issue (you may need to push an update to the pyNN requirements.txt as well since it specifies lazyarray>=0.2.6), but a variant of the test case above produces another error. I am unsure if the error is newly introduced or a separate issue.

The following error only occurs for population views with a single neuron in an MPI context.

**Variant Test Case**
```python
from pyNN.nest import *

population = Population(2, IF_cond_alpha())
population[0:1].set(tau_m = 20)
```

**Execution**
```
mpirun -np 2 test_case.py

...

Traceback (most recent call last):
  File "test_case.py", line 4, in <module>
    population[0:1].set(tau_m = 20)
  File ".../pyNN/common/populations.py", line 346, in set
    parameter_space = self.celltype.reverse_translate(self._get_parameters(*native_names))
  File ".../pyNN/nest/populations.py", line 51, in _get_parameters
    for col, name in enumerate(names))
  File ".../pyNN/nest/populations.py", line 51, in <genexpr>
    for col, name in enumerate(names))
IndexError: too many indices for array
```

**Comment by kennysharma** [comment]
Thanks again for the quick patches, the latest master f45e96c11e0be4d8e300ac9e881abb67e400ed0a (0.8.2 release) resolves all of our issues.

**Comment by kennysharma** [comment]
Sorry to bug you on this closed issue, but I forgot to ask if you have a timetable for when PyNN 0.8.2 will be available via pip?

**Comment by apdavison** [comment]
Sorry, I thought I had already uploaded it. 0.8.2 is available now via pip

**Comment by kennysharma** [comment]
Thanks! Everything is working as expected.
