### ISSUE TITLE
documentation on public facing website doesnt match up with 0.8.0 -rc1 or above

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#444]
the record method: http://neuralensemble.org/docs/PyNN/reference/populations.html
doesn't correspond to this: https://github.com/NeuralEnsemble/PyNN/blob/4b4a953b10fe3b2a4358cc3a50c7867fb536ad36/pyNN/common/procedural_api.py#L65

**Comment by apdavison** [comment]
The `Population.record()` method is here:
  https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/common/populations.py#L414

The code you've linked to is the top-level `record()` function, which is not documented - see
https://github.com/NeuralEnsemble/PyNN/blob/master/doc/recording.txt#L59

I'll leave the ticket open and close it once the `record()` function is documented.

**Comment by alan-stokes** [comment]
hi Andrew, ah, that'll explain the Jamie code i'm looking at, I'm trying to
figure out where everything is linked. Thanks for the clarification, means
i can document our version with the correct description of source and
filename once this ticket is closed then.

Alan

**Comment by apdavison** [comment]
Documentation of `record()` in ad989047e809118afe5c8fba9be84cc26618b641

This will appear in the public documentation next time it is rebuilt.
