### ISSUE TITLE
issue with checkout / zip of master via aux file

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#446]
Hi all, 

so been doing some fiddling on my setup and needed to checkout your master again. Unfortunately this fails with a error about not finding aux.py from pynn/hardware/aux.py

even if i download a zip version of your code, and then try unzipping the files to any location, i get the same error from the unzipper or the github checkouter.
after much exploration, it seems AUX is a keyword used by windows, and so wont let you create a file/folder with that name. so this makes PyNN master a linux only support currently.

Must have been lucky that the other times i was in linux when i did the download, but at moment my linux partition is being more trouble than its worth.

regards
Alan

**Comment by apdavison** [comment]
fixed by #678
