### ISSUE TITLE
recording file symantics

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#449]
Hi all,

still looking into the recording interface for getting the spinnaker version of PyNN 0.8 one up and running, and saw what may be a semantic implication mismatch.

when you say record, your adding new atoms to be recorded (grand)
but your also able to add a outputfile (tofile=None). This tofile parameter if filled is sent to the recording interface on its own (with no context to which variable is being recorded). Therefore it overrides all previous set tofiles, as its just a basestring, not say a tuple or dict nor a function call with the variable name attached. so the following calls results in what id believe end users would say is unexpected behavior

pop.record("spikes",  tofile="spikes.txt")
this sets spikes to go to spikes.txt
pop.record('v', tofile="v.txt")
this sets spikes and v to go to v,.txt
whereas as a end user, id expect spikes to go to spikes.txt and v to go to v.txt

the reasoning why i think this behavior is going to happen is from here:
https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/common/populations.py#L439-L440
as this sets the file for the recorder, but without any context to which variable its being recorded for and is the only place where tofile is handed down to the recorder interface. 

regards
Alan

**Comment by apdavison** [comment]
Hi Alan,

Your expectation as an end user is correct; this is an implementation bug. I think the reason it hasn't come to light earlier is that normally you would only call `population.record()` once, e.g.
```python
pop.record(["spikes", "v"], to_file="data.h5")
```

Andrew
