### ISSUE TITLE
`find_units()` only covers recordable variables, not neuron parameters

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#459]
hi all, 

sorry to be the bearer of bad news again, but found another niggle issue in the interface. 

we support for a population find_units(variable) 
(http://neuralensemble.org/docs/PyNN/reference/populations.html, 
https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/common/populations.py#L407-L408)

the documentation has no details here of its scope or return value, which is a bit bad, but as a end user, id expect this to be able to tell me the units for say v_init, i_offset etc. But the code to date only support v, gsyn exc, gsyn inh 
(https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/standardmodels/cells.py#L123-L127)

so these need to be expanded to support the gathering of units for the state parameters of the cell as well as the recorded parameters. 

regards
Alan

**Comment by apdavison** [comment]
This sounds like a useful extension.

**Comment by appukuttan-shailesh** [comment]
Fixed in #496

**Comment by Amenty** [comment]
When I am typing print("a::::", find_units(a)), I am getting: NameError: name 'find_units' is not defined

**Comment by apdavison** [comment]
Hi @Amenty, `find_units` is not a function, it is a method of the Population class, so it should be something like `pop.find_units('a')`, where `pop` is a Population.

**Comment by Amenty** [comment]
@apdavison Many thanks! Now it is clear.

**Comment by Amenty** [comment]
I have tried it, and with this:

cell = Population(1, EIF_cond_alpha_isfa_ista, cellparams=cell_params, initial_values={'v': V_INIT})
cell.find_units('a')

I am not getting an error message, but also I am not getting any output as well...

**Comment by appukuttan-shailesh** [comment]
Just for clarity on this thread, PyNN currently returns `'nS'` for the parameter `a` specified above. This is discussed further in #620 .
