### ISSUE TITLE
ValueError in Population initialize using get After set in MPI Context

### ISSUE THREAD

**Issue by kennysharma** [NeuralEnsemble/PyNN#463]
Sorry for the horrible title, I'm not 100% sure this is a bug or just a rather specific use case. I'd be happy to take workaround feedback if you don't think this is a bug.

Here's a minimal example:

```python
import pyNN.nest as sim 
population = sim.Population(100, sim.IF_cond_alpha())
population[0:50].set(v_rest=-100)
sim.initialize(population, v=population.get('v_rest'))
```

On  a single process setup this runs fine, but when run within an MPI context:

```bash
mpirun -np 2 minimal.py
...
ValueError: Array has shape (100,), value has shape (50,)
ValueError: Array has shape (100,), value has shape (50,)
```

The issue seems to be:

- Population.set(...) -> generates a heterogenous population where parameters are stored in an array of size(population) rather than a single value for a homogenous population
- Population.get(...) -> only returns the values for local cells (I know I can use gather=True, but...)
- Population.initialize(...) -> seems to try to set values on all cells rather than just local cells

So my main question would be, should initialize be MPI aware and only except an array of values of size (local_cells)?

In the interim I can likely modify the code to workaround this issue by using a PopulationView of local cells only as the first parameter, or would you suggest a different solution?

**Comment by apdavison** [comment]
This is the expected behaviour at present (i.e. you are expected to either use `gather=True`, initialize the `PopulationView` separately, or use a lazy array, e.g.
```
v_rest = lambda i: np.where(i < 50, -100.0, -80.0)
population.set(v_rest=v_rest)
sim.initialize(population, v=v_rest)
```
)

I'm happy to consider making `initialize()` MPI aware, but there may well be other parts of the API that should also be MPI-aware, and I would prefer to make the changes all at once for the sake of consistency. I will therefore close this ticket and create a new, more general one.

**Comment by apdavison** [comment]
New ticket is #464

**Comment by kennysharma** [comment]
That makes sense to me, I'll let you know if there are any other specific issues that we run into in the future, but we can work around them easily enough for now.
