### ISSUE TITLE
pynn 0.75 doc page seems to have gone missing

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#468]
over the years, this link has always worked to get me to the pynn 0.75 documentation. 
http://neuralensemble.org/trac/PyNN/wiki/API-0.7

today this link goes to a 404 error. 

for backwards support, this link should either give a page stating where the pynn 0.75 docs have gone to, or even better, having a auto redirect to the new location.

**Comment by apdavison** [comment]
The 0.7 docs are now at http://neuralensemble.org/docs/PyNN/0.7/

The API docs are now at http://neuralensemble.org/docs/PyNN/0.7/api/api-0.7.html

Adding a redirect is on my todo list...

**Comment by alan-stokes** [comment]
thank you for the new locations. hopefulyl this issue will catch the rest who go there before you get flooded with the same question.

regards
Alan

**Comment by alan-stokes** [comment]
Hi Andrew, 

your links are down again. Have they moved again?

regards
Alan

**Comment by apdavison** [comment]
Thanks for spotting that Alan. They’re back up in the same place!
