### ISSUE TITLE
verbose parameter in connections 

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#469]
This is a little one which was found whilst trying to document the connections fully. 

pynn 0.75 connections has a verbose parameter which is never defined in docs of pynn 0.75 api, or docs. The source code neither states what its for.

Its removed in 0.8 connections, but for completeness sake, could we have a description of what verbose was, and maybe the docs updated to define it? please and thank you

regards
Alan

**Comment by apdavison** [comment]
Sorry about that, it was described only in the release notes - see under http://neuralensemble.org/docs/PyNN/releases/0.7.html#details

**Comment by apdavison** [comment]
Note that it has been replaced in PyNN 0.8+ by the more general `callback` parameter.
