### ISSUE TITLE
running pynn 0.83 issue

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#471]
When installing pynn 0.83 to test spinnaker pynn 0.8 interface, it causes issue with the new neo form. 

The requirements.txt states the following:

neo>=0.3

it should state:
neo>=0.3<0.4

as the 0.4 install causes pynn 0.83 to crash when trying to import its plotting parts. 

regards
Alan

**Comment by apdavison** [comment]
The PyNN 0.8 branch is no longer maintained, since the 0.9 API is almost identical.
