### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'rate'

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#478]
I installed brian and then pyNN(both with pip install). I used the code from  [here](http://neuralensemble.org/docs/PyNN/data_handling.html). I replaced import pyNN.neuron as sim with import pyNN.brian as sim.
I get an error. 
`p_in = sim.Population(10, sim.SpikeSourcePoisson(rate=10.0), label="input")
TypeError: __init__() got an unexpected keyword argument 'rate'`

I am not sure what wrong i'm doing!

**Comment by appukuttan-shailesh** [comment]
Could you let us know the following:
1) Which version of PyNN are you using? Could you confirm whether the same error is obtained with v 0.9.
2) Which snippet of code where you trying to execute on [this page](http://neuralensemble.org/docs/PyNN/data_handling.html)? I tried the first two, and both were working for me with Brian and NEST. The first example currently gives an error when running via NEURON. The bug will be fixed soon.

**Comment by appukuttan-shailesh** [comment]
@ruthvik92 : could you confirm whether you still encounter this problem. If so, do let us know which snippet of code were you trying to execute on that page.

**Comment by ruthvik92** [comment]
Hi, 
Sorry for the late reply. I got this error when i try installing the software using pip but when i install it by downloading from github and installing it using shell i  don't have error.

**Comment by apdavison** [comment]
Thanks for the feedback. It seems the problem was fixed in the latest PyNN, so we can close this ticket.

**Comment by ar8372** [comment]
Hi, I encountered the same error. I have upgraded version of tensorflow but still no solution found.  
Below I am printing version of tensorflow and related, my linux system has. (I ran `conda list` to get the version detail)
```
tensorflow                2.9.1                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-gpu            2.9.1                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
```

The error I get is as follows:
on this line: `xi = Dropout(rate=0.25)(xi)`
I am getting this error: 

```
    xi = Dropout(rate=0.25)(xi)
TypeError: __init__() got an unexpected keyword argument 'rate'
```

Please let me no if my query is not clear. 

Thanks,

**Comment by apdavison** [comment]
@ar8372 I think you've posted this in the wrong repository. PyNN does not use tensorflow in any way.
