### ISSUE TITLE
Possible unhandled error in _delay_correction() under pyNN.NEST 

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#482]
This is related to the issue raised here: https://github.com/OpenSourceBrain/IzhikevichModel/issues/6
If the intended timestamps (for StepCurrentSource say) are:
```
Model times =  [  0.00000000e+00   1.00000000e-02   2.00000000e-02 ...,   3.12500000e+02
   3.12510000e+02   4.00000000e+02]
```
_delay_correction() currently adjusts this for pyNN.NEST as:
```
pyNN times =  [  0.00000000e+00   0.00000000e+00   1.00000000e-02 ...,   3.12490000e+02
   3.12500000e+02   3.99990000e+02]
```
leading to multiple 0.0 timestamps. This causes errors as the timestamps need to be monotonically increasing.

@apdavison : I am considering a fix which will remove all 0.0's (and their corresponding amplitudes) and retain only the _last_ 0.0 and its corresponding amplitude. This is because the earlier amplitudes will never actually come into play, and will be overwritten with the last one. Do you think this would be ok?

**Comment by apdavison** [comment]
Yes, that sounds like a good fix.

**Comment by appukuttan-shailesh** [comment]
Fixed that bit, but it seems there is an additional problem with handling floating point numbers (resolution for comparing floats).
