### ISSUE TITLE
documentation is wrong!

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#486]
http://neuralensemble.org/docs/PyNN/reference/projections.html

even though the init list does not include a RNG, it is then listed in the more explicit definitions of the params. Assuming this is a left over from PyNN 0.75. 

rng
The RNG object that was used by the Connector.

thanks to @Christian-B for finding this during a test

**Comment by apdavison** [comment]
It's not wrong, it's just badly formatted. The arguments to the constructor are in italic. The names in bold are attributes of the Projection object, e.g. `projection.rng`

**Comment by alan-stokes** [comment]
ah, then i stand correct my old friend. we were trying to figure out how to
set a rng in pynn 0.8 vs pynn 0.75 for testing our new shiny interface.

thanks for the clarification.

regards
Alan

p.s. we've been building some slides for trying to identify the
differences. would you want a gander to see if we've missed anything /
clarify if we've misunderstood anything. or for usage by yourself etc.

**Comment by apdavison** [comment]
> we've been building some slides for trying to identify the
> differences. would you want a gander...?

yes please - might be useful for adding a "migrating from PyNN 0.7 to 0.8/0.9" page to the documentation (extending/improving http://neuralensemble.org/docs/PyNN/releases/0.8.0.html)
