### ISSUE TITLE
Difference in implementation of AC source in NEST 

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#497]
For the AC source, there is a difference in the way in which NEST uses the specified phase and frequency. It evaluates the signal from t = 0, irrespective of start/stop. They say:

> In NEST, start and stop strictly do windowing and origin strictly moves this window. Thus, time is always counted from 0 when computing the sinusoid.

Brian and NEURON, on the other hand, handle this differently with the signal being computer from t_start. @apdavison : Do we retain these differences and keep them true to the simulators, or do we want the outputs to be similar?

Related post (with sample output): https://github.com/nest/nest-simulator/pull/730

**Comment by apdavison** [comment]
I would prefer to keep the current PyNN interpretation of the parameters, which will require sending a modified phase to NEST.

**Comment by gtrensch** [comment]
@apdavison for more detailed NEST-related information on this issue, please see also the comment from @heplesser on May 24th in the following NEST pull request: https://github.com/nest/nest-simulator/pull/730 and the related issue https://github.com/nest/nest-simulator/issues/505
