### ISSUE TITLE
Misleading documentation for the space module

### ISSUE THREAD

**Issue by anandtrex** [NeuralEnsemble/PyNN#504]
In the documentation for the [space module](http://neuralensemble.org/docs/PyNN/space.html), it says 

> BY default, grid positions are filled sequentially, iterating first over the z dimension, then y, then x, but we can also fill the grid randomly:

BUT, in PyNN 0.9.1, using `fill_order='random'` results in a `NotImplementedError`.

**Comment by apdavison** [comment]
Fixed in 3e6728f
