### ISSUE TITLE
 IndexError: list index out of range,   Getting membrane potential data while simulation is in progress.

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#508]
On the lines of an example given [here](http://neuralensemble.org/docs/PyNN/examples/simple_STDP.html) I am trying to record the membrane potentials for a particular sampling intervals. I used the method `get_data('v') ` to record membrane potential of all the cells in a  population. I got the following error. 

```
File "/usr/local/lib/python2.7/dist-packages/pyNN/common/populations.py", line 499, in get_data
    return self.recorder.get(variables, gather, self._record_filter, clear)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/recording/__init__.py", line 307, in get
    data.rec_datetime = data.segments[0].rec_datetime
IndexError: list index out of range
```
Is there any way to record membrane potential while the simulation is in progress, similar to recording weights in the example provided in the above link?

**Comment by apdavison** [comment]
Please can you post the code which gives this error? (or a minimal example which shows the same error)

**Comment by ruthvik92** [comment]
Hi,
I was trying to access membrane potential during the simulation, which I think is not possible from your reply to my comment on the other post.

This line is what's giving me the error: I just assumed the membrane potential from the population calss is also accessible like the weights from the projection class proving that I was wrong in my assumption.

`self.accum_volts.append(self.population.get_data('v_reset').filter(name='v')[0])`

I was have this line in my callback function to retrieve weights and potential.

**Comment by apdavison** [comment]
Based on the error message, I would guess that you did not call `self.population.record('v')` before calling `run()`

**Comment by ruthvik92** [comment]
Yes, that was the problem, this post is related to issue #390. Now, I can access spike times and membrane potentials before I call `run()`. I made some changes to **Neuron** as you suggested. You can close this.
