### ISSUE TITLE
Error during compilation of NEST extensions

### ISSUE THREAD

**Issue by deep-introspection** [NeuralEnsemble/PyNN#510]
Hi!

Configuration: NEST 2.12.0_2 installed through Homebrew/Science on OSX Sierra 10.12.6
Compilation of the pyNN/NEST module during setup could not locate the slifunction.h
Here is the error I get during setup install:

```
nest-config found at /usr/local/bin/nest-config
Unable to compile NEST extensions. Output was:
  [ 25%] Building CXX object CMakeFiles/pynn_extensions_module.dir/pynn_extensions.cpp.o
  In file included from ./PyNN/build/lib/pyNN/nest/extensions/pynn_extensions.cpp:8:0:
  ./PyNN/build/lib/pyNN/nest/extensions/pynn_extensions.h:12:10: fatal error: slifunction.h: No such file or directory
   #include "slifunction.h"
            ^~~~~~~~~~~~~~~
  compilation terminated.
  make[2]: *** [CMakeFiles/pynn_extensions_module.dir/pynn_extensions.cpp.o] Error 1
  make[1]: *** [CMakeFiles/pynn_extensions_module.dir/all] Error 2
  make: *** [all] Error 2
```

Everything else run smoothly and I can import Nest in Python.
Thanks for your time,
Guillaume

**Comment by deep-introspection** [comment]
For information, `nest-config --includes` gives:
` -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/libnestutil -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/build/libnestutil -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/librandom -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/sli -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/topology -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/nestkernel -I/tmp/nest-20170818-83823-drzjlz/nest-2.12.0/nest -I/usr/local/include -I/usr/local/opt/readline/include -I/usr/local/include -I/usr/local/Cellar/open-mpi/2.1.0/include`

I guess the installation from Homebrew does not leave the necessary .h files to allow proper compilation of the pyNN Module.

**Comment by apdavison** [comment]
I don't use Homebrew, and so cannot attempt to reproduce the problem. Could you ask about this on the [NEST mailing list](http://www.nest-simulator.org/community/), as this problem doesn't appear to be specific to PyNN?
