### ISSUE TITLE
Updating StepCurrentSource across all simulators

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#512]
`StepCurrentSource` currently exhibits certain variations in its behavior across the various simulators. In view of this, it would be useful to handle the following within PyNN, rather than leaving it to the individual simulators:
1. Ensure that all time stamps are non-negative
2. Ensure that times provided are of strictly increasing magnitudes
3. Provide a mapping of provided timestamps to actual simulation time instants based on specified `dt`

@apdavison : Do you recommend any other changes on this front?

Will post some of the discrepancies currently observed in another post soon.

**Comment by appukuttan-shailesh** [comment]
**Current discrepancies**
Note: dt = 0.1 ms
- Example 1: Brian
`step = StepCurrentSource(times=[0.55, 0.85], amplitudes=[0.6, 0.4])`
Problem: _No current injected_
![brian_1](https://user-images.githubusercontent.com/24866517/29880411-fbce1f52-8da7-11e7-84c8-1d67d51d8639.png)

- Example 2: NEURON
`step = StepCurrentSource(times=[0.55, 0.85], amplitudes=[0.6, 0.4])`
Problem: _0.55 mapped to 0.6, while 0.85 mapped to 0.8_
![neuron_1](https://user-images.githubusercontent.com/24866517/29880581-6b4f2ce0-8da8-11e7-83e2-df7359f67792.png)
_

**Comment by appukuttan-shailesh** [comment]
One of the problems would be when a user specifies times as:
`step = StepCurrentSource(times=[0.2, 0.42, 0.44, 0.6], amplitudes=[0.6, 0.4, 0.6, 0.4])`

For `dt = 0.1`, both `0.42` and `0.44` would need to be mapped to `0.4`. If so, then this would require us to remove all the duplicate time instants (save the last instance) and their corresponding amplitudes, after mapping.
So,
`times=[0.2, 0.42, 0.44, 0.6]`
`amplitudes=[0.6, 0.4, 0.6, 0.4])`

would get mapped to:
`times=[0.2, 0.4, 0.4, 0.6]`
`amplitudes=[0.6, 0.4, 0.6, 0.4])`

and then be reduced to:
`times=[0.2, 0.4, 0.6]`
`amplitudes=[0.6, 0.6, 0.4])`

@apdavison : Shall I proceed with this approach?

**Comment by apdavison** [comment]
Yes, please go ahead.
