### ISSUE TITLE
Unable to use Nest with pyNN

### ISSUE THREAD

**Issue by ShashShukla** [NeuralEnsemble/PyNN#520]
I am running Ubuntu 16.04 LTS
I have successfully installed NEST 2.12.0 with Anaconda Python, by building from the master branch. 
I then installed pyNN using pip. 

But, "import pyNN.nest as sim" gives:

```
CSAConnector: libneurosim support not available in NEST.
Falling back on PyNN's default CSAConnector.
Please re-compile NEST using --with-libneurosim=PATH
/home/shashwat/anaconda2/lib/python2.7/site-packages/pyNN/nest/__init__.py:54: UserWarning: Unable to install NEST extensions. Certain models may not be available.
Further details: DynamicModuleManagementError in Install: Module 'pynn_extensions' could not be opened.
The dynamic loader returned the following error: 'file not found'.

Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!
  warnings.warn("Unable to install NEST extensions. Certain models may not be available.\nFurther details: {}".format(err))
```

The pyNN installation page(http://neuralensemble.org/docs/PyNN/installation.html) says that this can be resolved by adding nest-config to PATH. I have added the path to nest-config to PATH as well as LD_LIBRARY_PATH.
Hence the relevant part of my .bashrc file looks like: 

```
#For NEST
LD_PRELOAD=/lib/x86_64-linux-gnu/libncursesw.so.5
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shashwat/Documents/NEST/lib

#For pyNN
export PATH="/home/shashwat/Documents/NEST/bin:$PATH" 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shashwat/Documents/NEST/bin```


Any help would be appreciated, thanks!

**Comment by apdavison** [comment]
Just to note, the NEST master branch is not 2.12.0 (even though that is the version string it gives when you build it), it is preparing a future release of NEST (2.12.1 or 3.0.0, I'm not sure which). You can use this with PyNN, but then you need to install PyNN from the `nest-dev` branch in Github. To install NEST 2.12.0 you should install from the [tar.gz archive](https://github.com/nest/nest-simulator/releases/download/v2.12.0/nest-2.12.0.tar.gz)

Concerning the warnings, they are only a problem if you want to use the `GIF_cond_exp` model or the optimized `CSAConnector`. All other models, and the non-optimized `CSAConnector` should work.

Concerning the nest-config problem, one thing I note is that for PyNN it should be
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shashwat/Documents/NEST/lib`
not
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shashwat/Documents/NEST/bin`

Does changing this and reinstalling PyNN solve the problem?

**Comment by ShashShukla** [comment]
Thank you for bringing the nuance in NEST versions to my attention. I have now reinstalled NEST from the above tar.gz archive as you suggested.
Subsequently, I uninstalled and again installed pyNN via pip.

Regarding the .bashrc, the pyNN installation page says that nest-config must be in PATH. This is found in bin, and not in lib. 
Regardless, even after adding both to the LD_LIBRARY_PATH, **I am getting the same error.**
I even added both to PATH.
So now, my bash looks like:
```
export PATH="/home/shashwat/Documents/NEST/lib:$PATH"
export PATH="/home/shashwat/Documents/NEST/bin:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shashwat/Documents/NEST/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shashwat/Documents/NEST/bin

```

**Comment by ShashShukla** [comment]
What is interesting is that when I installed pyNN from the nest-dev branch, it solved the nest-config problem. The output that I now get is:
```
Type 'nest.help()' to find out more about NEST.
CSAConnector: libneurosim support not available in NEST.
Falling back on PyNN's default CSAConnector.
Please re-compile NEST using --with-libneurosim=PATH
```
This seems to indicate that the pip installation of pyNN is not compatible with Nest 2.12.0 (and of course with the NEST master branch). I am not sure if this has to do with using Anaconda Python. It might be that pyNN via pip works fine with vanilla python. This might be something worth looking into.
Regardless, I will get started with pyNN with this setup. 
Thank you for your help!

**Comment by Vafa-Andalibi** [comment]
I still have this problem. Installing it from the nest-dev branch doesn't solve the problem but just changes the error to warning. Any solution for this?

**Comment by apdavison** [comment]
If you install PyNN by downloading the tar.gz archive, and then running `python setup.py install` then the NEST extension modules are built provided `nest-config` is available.

In you install using `pip`, then for some reason the extension modules are not built. I am looking into this problem. Note that this does not stop you using PyNN with NEST, it only means that a couple of additional models are not available.

**Comment by apdavison** [comment]
@ShashShukla The warning message about libneurosim simply means that you have not built NEST with libneurosim support - see the NEST documentation for help on doing this.

libneurosim is only useful if your model uses the CSAConnector, as it will improve the speed of creating the connections.

**Comment by Vafa-Andalibi** [comment]
Thanks that solved my problem. i'm getting a warning for nrnivmodl which I assume is because I'm not having the NEURON installed since I'm just going to use NEST. Thanks again

**Comment by apdavison** [comment]
For future reference, one thing that may work is forcing pip to install from source, rather than from cached wheel packages, i.e.:
`pip install --no-use-wheel PyNN`

This will help in the situation where you ran `pip install PyNN` without having `nest-config` on the PATH, since then future calls to `pip install` will just re-install from the pip cache, rather than re-running the build stage. Using `--no-use-wheel` (or `--no-binary :all:`) forces pip to rebuild from source.
