### ISSUE TITLE
Issue with printing a projection instance

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#524]
PyNN allows to print Populations, e.g.
```
p = Population(10, IF_curr_exp(v_rest=-60))
print p
```
gives
```
Population(10, IF_curr_exp(<parameters>), structure=Line(y=0.0, x0=0.0, z=0.0, dx=1.0), label='population2')
```

But if we try to print a projection, such as:
```
myprj = Projection(pop1, pop2, FixedProbabilityConnector(0.2), StaticSynapse())
```
we get the error message:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position `XX`: ordinal not in range(128)
```

**Comment by apdavison** [comment]
The problem is that the locale is not set to use Unicode in your terminal.

Try
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

(other languages also work, e.g. `fr_FR.UTF-8`)

If your system doesn't have the `en_US.UTF-8` locale installed (run `locale -a` to see what is installed), you will have to install it (see, for example, https://wiki.debian.org/Locale)

**Comment by appukuttan-shailesh** [comment]
I am still not able to get this to work. I have:
`locale -a`

> C
> C.UTF-8
> en_AG
> en_AG.utf8
> en_AU.utf8
> en_BW.utf8
> en_CA.utf8
> en_DK.utf8
> en_GB.utf8
> en_HK.utf8
> en_IE.utf8
> en_IN
> en_IN.utf8
> en_NG
> en_NG.utf8
> en_NZ.utf8
> en_PH.utf8
> en_SG.utf8
> **en_US.utf8**
> en_ZA.utf8
> en_ZM
> en_ZM.utf8
> en_ZW.utf8
> fr_FR.utf8
> POSIX

and 
`locale` give

> LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
> 
Am I missing something?
