### ISSUE TITLE
Problem with using FixedTotalNumberConnector()

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#525]
I tried making projections by the following methods:
```
prj1 = Projection(pop1, pop2, FixedNumberPreConnector(10), StaticSynapse())
prj2 = Projection(pop1, pop2, FixedNumberPostConnector(10), StaticSynapse())
prj3 = Projection(pop1, pop2, FixedTotalNumberConnector(10), StaticSynapse())
```
But `FixedTotalNumberConnector` throws the error:
`TypeError: only integer scalar arrays can be converted to a scalar index`

**Comment by apdavison** [comment]
Which backend is this? And please can you post the full traceback?

**Comment by appukuttan-shailesh** [comment]
Unable to reproduce this error now. Shall close this now, and reopen later if it reoccurs.
