### ISSUE TITLE
Reverse STDP

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#526]
Hi,
I am trying to have plastic inhibition between populations if there is any causality. Can i use the  STDPMechanism  with -ve A_plus and -ve A_minus in the existing SpikePairRule?

**Comment by anandtrex** [comment]
@ruthvik92 Briefly testing the example given [here](http://neuralensemble.org/docs/PyNN/examples/simple_STDP.html) but setting negative A_plus and A_minus seems to do exactly what you want -- invert your STDP curve. See image:
![simple_stdp_nest_20170927-135323](https://user-images.githubusercontent.com/1858015/30912069-7345e6b6-a38b-11e7-8fed-2eb090d6f711.png)

**Comment by apdavison** [comment]
@ruthvik92 does the suggestion from @anandtrex work for you?

**Comment by ruthvik92** [comment]
Yes, I got it.
