### ISSUE TITLE
Nest Extension Module in PyNN

### ISSUE THREAD

**Issue by JuanC93** [NeuralEnsemble/PyNN#530]
Hi everyone! I'm Juan Carlos, a PhD student at the University of Granada.

In my researching group we work with Nest and PyNN. We have done some extension module in Nest but I wonder if these modules would be able use it in PyNN. In the main website of PyNN I haven't found anything. Can we use these modules in PyNN?

Thanks for the support.

**Comment by apdavison** [comment]
please see my answer to this question here: https://groups.google.com/forum/#!topic/neuralensemble/0JLwCYDcUbQ
