### ISSUE TITLE
pyNN.errors.NotLocalError: Cannot obtain parameters for a cell that does not exist on this node.

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#534]
I edited the file pyNN/neuron/populations.py file. I added extra functions(like setting custom membrane potentials, to know which all neurons spiked in the previous timestep etc.)  to make some decisions while the simulation is running using callbacks, part of that I have a function:
```python
def get_membrane_potential(self):
         return [cell._cell.v for cell in self.all_cells]
```

It works fine and I see what's expected when used in sequential mode. But, I want to parallelize the application, I tried to run it using mpi. I am using NEURON. 
mpirun -np 2 ~/neuron/nrn/src/nrniv/nrniv -mpi myfile.py
I would like to  edit further to support parallelization, any basic guidance will be very helpful, Here is the traceback:

```python
self.cell_voltages[items] = self.popltns[items].get_membrane_potential() 
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/populations.py", line 131, in get_membrane_potential
    return [cell._cell.v for cell in self.all_cells]
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/populations.py", line 63, in __getattr__
    val = self.get_parameters()[name]
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/populations.py", line 95, in get_parameters
    raise errors.NotLocalError("Cannot obtain parameters for a cell that does not exist on this node.")
pyNN.errors.NotLocalError: Cannot obtain parameters for a cell that does not exist on this node.
```

**Comment by apdavison** [comment]
On line 131, you should use `self.local_cells` instead of `self.all_cells`.

If you then want to gather the membrane potentials from all MPI nodes onto a single node, you should use the various `gather_X()` functions in `pyNN.recording`, and perhaps add a `gather` argument to `get_membrane_potential` to make this optional.

**Comment by ruthvik92** [comment]
I am using gather_array() in `pyNN.recording` to gather membrane potentials of each population. 
I get this error
```python
0 NEURON: usable mindelay is 0 (or less than dt for fixed step method)
0  near line 0
0  {initializer._initialize()}
                            ^
        0 finitialize()
Traceback (most recent call last):
  File "PySCNN_v17.py", line 314, in <module>
    p.run(t_stop, callbacks=[sparse_coding])
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 89, in run_until
    simulator.state.run_until(next)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/simulator.py", line 261, in run_until
    self._pre_run()
  File "/usr/local/lib/python2.7/dist-packages/pyNN/neuron/simulator.py", line 239, in _pre_run
    h.finitialize()
RuntimeError: hoc error
```
synaptic delays are all set to 1 and time_step=1, i didn't set any min_delay in `setup(..)`. I came across a post about this issue in NEURON's forum, it says [Remember that parallel only works if the minimum interprocessor NetCon delay is greater than dt](https://www.neuron.yale.edu/phpBB/viewtopic.php?f=31&t=3090). Is there anyway I could set NetCon delay using PyNN?

**Comment by apdavison** [comment]
PyNN is supposed to set `min_delay` for you if you do not set it in `setup()`.

As a workaround, set `min_delay=1.0`.

**Comment by ruthvik92** [comment]
I got it to work with values, `timestep = 0.5`, `min_delay=delay-1`, `delay = 1.5`, `delay` here means 
all the delays between synapses. 
I tried a few different values:
`timestep = 1.5`, `min_delay=delay-0.5`, `delay = 1.75`
gives me an error saying `min_delay(1.25) must be greater than timestep`

`timestep =1, min_delay=delay-0.5, delay=1.75`
gives me an error saying `There are connections with delays(1) shorter than the minimum delay(1.25)`

**Comment by apdavison** [comment]
`min_delay` should be a multiple of `timestep`. This is why the error message for the last case is strange.
