### ISSUE TITLE
Issues with FromFileConnector on NEST

### ISSUE THREAD

**Issue by cjenzen** [NeuralEnsemble/PyNN#538]
Hi,
when using the FromFileConnector on PyNN 0.9.1 with NEST 2.12 I found that using a connection file without header works perfectly, while a file with a header will lead to an error. However, trying a second time will work. The script reproducing the issue can be found below. Corresponding data files should be attached.

In addition, calling ```describe()``` on the connector will lead to an error (line 561 in connectors.py should be ```parameter_names = ('file', 'distributed')```.

Furthermore, (using python2.7) connections are extracted into memory at least two times: first, the full file is read into memory, then this is copied somewhere (correct me if I am wrong). For large lists of connections this can be a major problem. Could you think of any way of e.g. reading in and using the files linewise? 

Thank you for your efforts... Here is the script for reproducing the first error
``` python
#import pyNN.spiNNaker as p
import pyNN.nest as p
#import pyNN.hardware.spikey as p


p.setup()
pop = p.Population(8, p.IF_cond_exp, {}, label="pop")

#pop = p.Population(8, p.IF_facets_hardware1, {}, label="pop")
input = p.Population(8, p.SpikeSourceArray,
                     {'spike_times': [0,10,20]}, label="input")

conn = p.FromFileConnector("conn.txt")
conn2 = p.FromFileConnector("conn2.txt")

proj = p.Projection(input, pop, conn)
try:
	proj2 = p.Projection(input, pop, conn2, receptor_type = "excitatory")
except:
	print "_____________ Exception Case ________________"
	proj2 = p.Projection(input, pop, conn2, receptor_type = "excitatory")

pop.record("spikes")
#pop.record()

p.run(200)

print proj.get(["weight", "delay"], format="list")
print proj2.get(["weight", "delay"], format="list")
a = pop.get_data().segments[0].spiketrains
for i in a:
	print i
#print pop.getSpikes()
p.end()
```
[conn.txt](https://github.com/NeuralEnsemble/PyNN/files/1475555/conn.txt)
[conn2.txt](https://github.com/NeuralEnsemble/PyNN/files/1475556/conn2.txt)

**Comment by appukuttan-shailesh** [comment]
Thanks @cjenzen for providing the sample test code. Always makes things easier to test.

The problem with the column headers was owing to their specification using a dictionary in the file "conn2.txt" (the ordering of the column headers gets mixed up with a dict):
```
#columns={"weight", "delay"}
0 0 0.015 0.1
```
Things work if this is changed to a list or tuple:
```
#columns=["weight", "delay"]
0 0 0.015 0.1
```
We will update PyNN to throw an appropriate error message if it finds anything other than a list or tuple.

Thanks for highlighting the problem with `describe()` and also providing the fix. This has been included in the PR.

@apdavison : Could you comment on the loading of connections to memory?

**Comment by apdavison** [comment]
The idea behind reading the whole file into memory is to allow us to reorder the connections so as to call the simulator connection functions fewer times, since these calls often have considerable overhead. 

However, I don't remember if we ever benchmarked this approach to check if it really does save time. In addition, for a memory-constrained simulation, we might anyway wish to sacrifice network creation speed in favour of reduced memory footprint, as @cjenzen suggests.

I've created a new ticket for this: #549
