### ISSUE TITLE
Use of LazyArray with NEST, NEURON and Brian

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#542]
Need to verify if all three simulators (NEST, NEURON, Brian) make use of LazyArray. It appears that currently only NEST does this. See the test case for #517 on how this affects evaluation. The following might be a simple check for this:

```
from pyNN.utility import get_script_args

simulator_name = get_script_args(1)[0]
exec("from pyNN.%s import *" % simulator_name)

step = StepCurrentSource(times=[25.0, 75.0, 125.0], amplitudes=[0.05, 0.10, 0.20])
print len(step.times)               # Works for Brian and NEURON
print len(step.times.evaluate())    # NEST needs this; difference probably linked to use of LazyArray
```
We need to ensure that all three simulators make use of LazyArray.
@legouee : Do you want to look at this?

**Comment by apdavison** [comment]
To clarify, all three simulator backends *do* make use of lazyarray in most places; it is only in translating parameters of current sources that they do not.
