### ISSUE TITLE
Brian failing when recording >1 cell in population

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#544]
This file works fine when pop_size = 1, but fails when 2 or more:
https://github.com/OpenSourceBrain/PyNNShowcase/blob/572b65c8a564b27837cf801e3e52fd79f6d45463/PyNN/InputsTest.py#L22 
```
Traceback (most recent call last):
  File "InputsTest.py", line 41, in <module>
    sim.run(tstop)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/brian/simulator.py", line 57, in run_until
    self.run(tstop - self.t)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/brian/simulator.py", line 54, in run
    self.network.run(simtime * ms)
  File "/usr/local/lib/python2.7/dist-packages/brian/network.py", line 574, in run
    self.update()
  File "/usr/local/lib/python2.7/dist-packages/brian/network.py", line 518, in update
    f()
  File "/usr/local/lib/python2.7/dist-packages/brian/neurongroup.py", line 546, in reset
    self._resetfun(self)
  File "/usr/local/lib/python2.7/dist-packages/brian/reset.py", line 328, in __call__
    V[neuronindices] = self.resetvalue
ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (0,)

```

**Comment by apdavison** [comment]
The `ValueError` seems to be due to the latest NumPy. With NumPy 1.8.2 the problem was silent, with the result that `V` was not properly reset.

**Comment by apdavison** [comment]
This looks to me like a problem inside Brian. I'm not sure if Brian 1 is being updated any more - the last commit [here](https://github.com/brian-team/brian) is from 18 months ago.

I guess the workaround is to use an older version of NumPy with `pyNN.brian`, and I guess I should prioritise implementing Brian 2 support in PyNN.

**Comment by pgleeson** [comment]
Ok, understood. It also seems to be an issue with some of the standard PyNN examples, e.g. 
https://github.com/NeuralEnsemble/PyNN/blob/master/examples/simpleRandomNetwork.py.

**Comment by pgleeson** [comment]
I suppose an option is to put a warning in PyNN whenever the prian module is loaded that numpy==1.12.0 should be used...

@mstimberg I assume there are no plans to make a minor release update for Brian1 which is fully compatible with the latest numpy?

**Comment by mstimberg** [comment]
We are indeed not developing Brian 1 anymore, but given that a significant amount of Brian 1 code exists that will most likely never updated to Brian 2, doing a release keeping compatibility with numpy might be a good idea. I'll have a look whether the necessary fixes are simple or a lot of work. If they are too much work, we could at least push a new release that fails with a clear error message for too recent numpy versions. Thanks for letting me know in any case!

**Comment by mstimberg** [comment]
I just pushed a commit Brian's to [master branch](https://github.com/brian-team/brian) that should fix the problem in the reset. @pgleeson could you try out that version? If it works fine for you, I'll push a 1.4.4 release.

**Comment by pgleeson** [comment]
@mstimberg Have tested locally and it works fine for me.

**Comment by pgleeson** [comment]
Works fine with Brian v1.4.4
