### ISSUE TITLE
Number of local cells on each of the nodes

### ISSUE THREAD

**Issue by ruthvik92** [NeuralEnsemble/PyNN#547]
I  have 1 input population(with 729 neurons) and 30 output populations(each with 529 neurons). Input population is connected to all of the output populations and each of these connections is achieved through `ListConnector` . I am running with 8 nodes. For some reason I had to set/get voltages of cells during the simulation, I am using callbacks to perform setting/getting voltages. So, I created functions:
```python
def get_membrane_potential(self):
         return [cell._cell.v for cell in self.local_cells]
```
```python
    def set_membrane_potential(self, vals):
        for p in range(0,len(vals)):
            self.local_cells[vals[p][0]]._cell.v=vals[p][1]
```
argument `vals` should look like `[(neur_id1,voltage1),(neur_id2,voltage2)....]`. 

I wrote a function `allgather_array` in `recording/__init__.py` using MPI's `Allgatherv` to gather voltages of all cells onto all nodes for calculation purposes. 
```python
def allgather_array(data):
    mpi_comm, mpi_flags = get_mpi_comm()
    assert isinstance(data, numpy.ndarray)
    assert len(data.shape) < 3
    # first we pass the data size
    size = data.size
    sizes = mpi_comm.allgather(size) or []
    displacements = [sum(sizes[:i]) for i in range(len(sizes))]
    displaces = [sizes[i] for i in range(len(sizes))]
    gdata = numpy.empty(sum(sizes))
    mpi_comm.Allgatherv([data.flatten(), size, mpi_flags['DOUBLE']],
                     [gdata, (sizes, displacements), mpi_flags['DOUBLE']]
                     )
    if len(data.shape) == 1:
        return gdata, displacements, displaces 
    else:
        num_columns = data.shape[1]
        return gdata.reshape((gdata.size / num_columns, num_columns)), mpi_comm.rank
```
I imported `allgather_array` and `get_mpi_comm` functions to my main python script using `from pyNN import recording`. 

If I try  `print len(one of the output populations)` in the python main script, I get `529` on all the nodes but when i `print len(array of cell voltages acquired through the function get_membrane_potential)` I get `66, 66, 66, 66, 66, 66, 66, 67` on each of the 8 nodes, I was expecting  `print len(one of the output populations)` also to be `66, 66, 66, 66, 66, 66, 66, 67`. Am I doing something wrong? Is this the expected behaviour?

**Comment by apdavison** [comment]
The attribute you are looking for is `local_size` - see http://neuralensemble.org/docs/PyNN/reference/populations.html#pyNN.neuron.Population.local_size
