### ISSUE TITLE
'IF_cond_exp' object has no attribute 'nest_name'

### ISSUE THREAD

**Issue by andraderenew** [NeuralEnsemble/PyNN#558]
I have this issue(see below):

Renes-MacBook-Air-2:~ andraderenew$ python /Users/andraderenew/Desktop/nest\ works/pyNN/\ population.py 
[INFO] [2018.2.3 19:17:12 /tmp/nest-20171218-23550-cuzryg/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.2.3 19:17:12 /tmp/nest-20171218-23550-cuzryg/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:233 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2018.2.3 19:17:12 /tmp/nest-20171218-23550-cuzryg/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.2.3 19:17:12 /tmp/nest-20171218-23550-cuzryg/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Dec 18 2017 12:55:19

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'nest.help()' to find out more about NEST.
CSAConnector: libneurosim support not available in NEST.
Falling back on PyNN's default CSAConnector.
Please re-compile NEST using --with-libneurosim=PATH
/Users/andraderenew/miniconda3/lib/python3.6/site-packages/pyNN/nest/__init__.py:55: UserWarning: Unable to install NEST extensions. Certain models may not be available.
Further details: DynamicModuleManagementError in Install: Module 'pynn_extensions' could not be opened.
The dynamic loader returned the following error: 'file not found'.

Please check LD_LIBRARY_PATH (OSX: DYLD_LIBRARY_PATH)!
  warnings.warn("Unable to install NEST extensions. Certain models may not be available.\nFurther details: {}".format(err))
Traceback (most recent call last):
  File "/Users/andraderenew/Desktop/nest works/pyNN/ population.py", line 8, in <module>
    ctx_cells = sim.Population(100,cortical_type)
  File "/Users/andraderenew/miniconda3/lib/python3.6/site-packages/pyNN/nest/populations.py", line 114, in __init__
    super(Population, self).__init__(size, cellclass, cellparams, structure, initial_values, label)
  File "/Users/andraderenew/miniconda3/lib/python3.6/site-packages/pyNN/common/populations.py", line 663, in __init__
    self._create_cells()
  File "/Users/andraderenew/miniconda3/lib/python3.6/site-packages/pyNN/nest/populations.py", line 123, in _create_cells
    nest_model = self.celltype.nest_name[simulator.state.spike_precision]
AttributeError: 'IF_cond_exp' object has no attribute 'nest_name'

**Comment by apdavison** [comment]
Which version of PyNN is this?

**Comment by andraderenew** [comment]
pyNN 0.9.1

**Comment by apdavison** [comment]
Please could you try upgrading to PyNN 0.9.2?

If you still get the error, please post the script, or the simplest script that gives the same error.

**Comment by andraderenew** [comment]
when I try pip install pyNN --upgrade it says is up-to-date

**Comment by apdavison** [comment]
Please could you post the output of the following commands:
```
pip freeze
```
```
python -c "import pyNN; print(pyNN); print(pyNN.__version__)"
```

**Comment by andraderenew** [comment]
Renes-MacBook-Air-2:~ andraderenew$ pip freeze
alabaster==0.7.10
apgl==0.8.1
appnope==0.1.0
asn1crypto==0.22.0
astroid==1.5.3
Babel==2.5.0
bleach==2.1.1
Brian2==2.1.2
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
conda==4.3.31
ConnPlotter==0.7a0
cryptography==2.0.3
csa==0.1.7
cycler==0.10.0
Cython==0.26.1
decorator==4.1.2
docutils==0.14
entrypoints==0.2.3
graphviz==0.8.1
html5lib==1.0.1
idna==2.6
imagesize==0.7.1
ipykernel==4.7.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.0.3
isort==4.2.15
jedi==0.10.2
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
lazy-object-proxy==1.3.1
lazyarray==0.3.2
MarkupSafe==1.0
matplotlib==2.0.2
mccabe==0.6.1
mglearn==0.1.6
mistune==0.8.1
mpi4py==3.0.0
mpmath==1.0.0
nbconvert==5.3.1
nbformat==4.4.0
nengo==2.6.0
nengo-gui==0.3.1
neo==0.5.2
networkx==2.1
NEURON==7.5
nose==1.3.7
notebook==5.2.0
numpy==1.13.3
numpydoc==0.7.0
olefile==0.44
opencv-python==3.3.0.10
pandas==0.21.0
pandocfilters==1.4.2
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.3.0
prompt-toolkit==1.0.15
psutil==5.4.1
ptyprocess==0.5.2
py-cpuinfo==3.3.0
pycodestyle==2.3.1
pycosat==0.6.2
pycparser==2.18
pydot==1.2.3
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.7.4
PyNEST==2.14.0
PyNN==0.9.2
pyOpenSSL==17.2.0
pyparsing==2.2.0
PySocks==1.6.7
python-dateutil==2.6.1
python-nest==3.4.0
pytz==2017.2
pyzmq==16.0.3
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
quantities==0.12.1
requests==2.18.4
rope==0.10.7
ruamel-yaml==0.11.14
scikit-learn==0.19.1
scipy==1.0.0
simplegeneric==0.8.1
six==1.10.0
sklearn==0.0
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.4
sympy==1.1.1
terminado==0.6
testpath==0.3.1
Topology==2.14.0
tornado==4.5.2
traitlets==4.3.2
typing==3.6.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.0.6
wrapt==1.10.11
Renes-MacBook-Air-2:~ andraderenew$ python -c "import pyNN; print(pyNN); print(pyNN.__version__)"
<module 'pyNN' from '/Users/andraderenew/miniconda3/lib/python3.6/site-packages/pyNN/__init__.py'>
0.9.2

**Comment by apdavison** [comment]
ok, so you are using PyNN 0.9.2.

Please could you now post the script, or the simplest script that gives the same error.

**Comment by andraderenew** [comment]
is the same one as the beginning of this GitHub pull request

**Comment by apdavison** [comment]
Please post here the contents of the file `/Users/andraderenew/Desktop/nest\ works/pyNN/\ population.py`

**Comment by andraderenew** [comment]
import pyNN.nest as sim
from pyNN.random import RandomDistribution
from pyNN.random import NumpyRNG

refractory_period = RandomDistribution('uniform', [2.0, 3.0], rng=NumpyRNG(seed=4242))
ctx_parameters = {'cm': 0.25, 'tau_m': 20.0, 'v_rest': -60, 'v_thresh': -50, 'tau_refrac': refractory_period,'v_reset': -60, 'v_spike': -50.0, 'a': 1.0, 'b': 0.005, 'tau_w': 600, 'delta_T': 2.5,'tau_syn_E': 5.0, 'e_rev_E': 0.0, 'tau_syn_I': 10.0, 'e_rev_I': -80 }
cortical_type = EIF_cond_exp_isfa_ista(**ctx_parameters)

ctx_cells = sim.Population(100, cortical_type)

**Comment by apdavison** [comment]
ok, I've run your script, and I do not get any error. If you're still getting an error on your machine, please can you run the script with debugging, i.e.
`python -m pdb /Users/andraderenew/Desktop/nest\ works/pyNN/\ population.py`
then at the `(Pdb)` prompt type:
`(Pdb) self.celltype.__class__`
and let me know what you see.

**Comment by andraderenew** [comment]
it gives me an error (I don't know how to debug) perhaps it´s a dumb issue



Last login: Tue Feb 27 20:22:54 on ttys000
Renes-MacBook-Air-2:~ andraderenew$ python -m pdb /Users/andraderenew/Desktop/nest\ works/pyNN/\ population.py
> /Users/andraderenew/Desktop/nest works/pyNN/ population.py(1)<module>()
-> import pyNN.nest as sim
(Pdb) self.celltype.__class__
*** NameError: name 'self' is not defined
(Pdb) celltype.__class__

**Comment by apdavison** [comment]
I think you need to type "continue" (or just "c") at the first (Pdb) prompt. It should then stop when it encounters an Exception, and then you can type `self.celltype.__class__`

**Comment by andraderenew** [comment]
I do it and it gives me the same name self is not defined

**Comment by apdavison** [comment]
Please post the full output you get.

**Comment by apdavison** [comment]
Closing this for now. I'm happy to reopen it, but at the moment I don't have enough information to reproduce the problem.
