### ISSUE TITLE
Link to publications? Lost with wiki?

### ISSUE THREAD

**Issue by NickleDave** [NeuralEnsemble/PyNN#592]
Hi PyNN devs,

The landing page of the docs (https://neuralensemble.org/PyNN/) has a link to publications (http://neuralensemble.org/trac/PyNN/wiki/Publications) but it seems to be dead.

Looks like at some point the wiki got shut down? I tried to figure out what happened from older issues and found some with links of the form `/wiki/$something` that no longer work either.

If that page is still around somewhere, I'd like to see it. Maybe I could submit a PR that adds the page back in .rst format to fix the link, if that would be helpful.

Thanks!

**Comment by apdavison** [comment]
Hi @NickleDave  - yes, we shut down the Trac once everything (or so we thought!) had been moved to Github / Sphinx.

We do have a backup of the wiki somewhere, but I found the Wayback Machine had made a copy: https://web.archive.org/web/20170227062815/http://neuralensemble.org/trac/PyNN/wiki/Publications

I would happily take you up on your offer to submit a PR adding this to the Sphinx docs.

**Comment by apdavison** [comment]
Implemented in #593
