### ISSUE TITLE
when i run the pyNN ，Display Illegal instruction

### ISSUE THREAD

**Issue by Jonsnow-zhang** [NeuralEnsemble/PyNN#594]
linaro@linaro-gnome:/data/PyNN-master/examples$ python Izhikevich.py --plot-figure nest
[INFO] [2018.9.6 1:52:21 /data/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.9.6 1:52:21 /data/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:233 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2018.9.6 1:52:21 /data/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2018.9.6 1:52:21 /data/nest-simulator-2.14.0/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Sep  5 2018 22:55:25

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'nest.help()' to find out more about NEST.
CSAConnector: libneurosim support not available in NEST.
Falling back on PyNN's default CSAConnector.
Please re-compile NEST using --with-libneurosim=PATH

Sep 06 01:52:29 SimulationManager::run [Warning]: 
    The requested simulation time is not an integer multiple of the minimal 
    delay in the network. This may result in inconsistent results under the 
    following conditions: (i) A network contains more than one source of 
    randomness, e.g., two different poisson_generators, and (ii) Simulate is 
    called repeatedly with simulation times that are not multiples of the 
    minimal delay.
Illegal instruction

linaro@linaro-gnome:/data/PyNN-master/examples$ python random_distributions.py nest
Illegal instruction
linaro@linaro-gnome:/data/PyNN-master/examples$

**Comment by apdavison** [comment]
I am unable to reproduce this. I suspect there is a problem with your NEST installation. Do you get the `Illegal instruction` message when you just `import nest`?

If not, please could you try to find the minimal script that gives the error?

**Comment by Jonsnow-zhang** [comment]
When I type "python Izhikevich.py --plot-figure nest"  ,it show "Illegal instruction" the "Illegal instruction" shows at the end.if I type "python Izhikevich.py nest" it not.   No matter what the situation, they will generate a xxxxxx.pkl file, but will not generate an image.

**Comment by apdavison** [comment]
I think this is a problem with your matplotlib installation, it is not related to PyNN as far as I can see.
