### ISSUE TITLE
outdated line in documentation

### ISSUE THREAD

**Issue by laurentperrinet** [NeuralEnsemble/PyNN#595]
Hi,
A small issue on the documentation: It specifies that for NEST by default the 'on_grid' is chosen

https://github.com/NeuralEnsemble/PyNN/blob/2d5997f03a83ffd7fd15553f96df703efce04ae9/doc/backends/NEST.txt#L29

while the code specifies a 'off_grid' by default (and this is correctly specifies in the docstring of the corresponding object's initialization function.

Cheers,
Laurent

**Comment by apdavison** [comment]
Fixed in 8121a4c
