### ISSUE TITLE
Create neuroml branch here for stable neuroml+master version

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#600]
@apdavison While I develop the neuroml functionality in https://github.com/pgleeson/PyNN, and open pull requests to master here when it's tested, it would be good to have a branch in the main PyNN repo which can be used for a location of a stable/tested version of **both** master here and my changes (in case they go out of sync). 

I need a stable branch to point at in various places including:
OMV: https://github.com/OpenSourceBrain/osb-model-validation/blob/master/omv/engines/getpynn.py
Docker for OSB: https://github.com/OpenSourceBrain/neuralensemble-docker/blob/python2/osb/Dockerfile#L94

**Comment by apdavison** [comment]
@pgleeson I've added you to the PyNN developers' team, so you should now have sufficient permissions to create a neuroml branch here.

**Comment by pgleeson** [comment]
Great, thanks. BTW, is there an ETA on a 0.9.3 release?

**Comment by apdavison** [comment]
I don't have a date in mind, but I don't think there's any reason to delay it, and there've been quite a few changes since 0.9.2. I'll try to find time next week or the week after.
