### ISSUE TITLE
Update or remove the README file in the `test` directory.

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/PyNN#607]
It is very out of date. Probably best to remove it or have just a pointer to the docs.

**Comment by GRsni** [comment]
Hi! I'd like to solve this issue. Should I just remove the README, or try to update its content?

**Comment by apdavison** [comment]
Fixed in #609. Many thanks @GRsni

**Comment by GRsni** [comment]
Glad I could help!
