### ISSUE TITLE
Parallel installation of py2 and py3 builds for nest extensions

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/PyNN#615]
Since PyNN supports both py2 and py3, and nest can also be built with both, do we need to differentiate between the extensions that are built with py2 and ones that are built with py3, (or does it not matter)?

Currently, the shared objects for the extension are simply called `libpynn_extensions.so` and `pynn_extensions.so`. For `libneurosim`, we modified the build system to produce `libpy2neurosim` and `libpy3neurosim` to differentiate between the two.

I don't see anything python specific in the extension code, but nest loads the shared object at runtime, so I do think the version of python the extensions were built with will make a difference?

**Comment by apdavison** [comment]
I'm not sure I understand what the use case is. Is it that you wish to be able to run PyNN with both Python 2 and Python 3 in the same environment?

(I've never encountered this as a problem, as I always install PyNEST within a virtualenv or conda environment, but I'm happy to make changes - could you make a pull request?)

**Comment by sanjayankur31** [comment]
Yes---when not using a conda environment and simply using the FHS locations, since both py2 and py3 builds generate the same module, they cannot be installed together.

This isn't too relevant now tbh. We're only providing py3 builds since py2 will be EOL soon. Closing.
