### ISSUE TITLE
`simple_stochastic_synapse` in nest extension now available in NEST as `bernoulli_connection`

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/PyNN#616]
A synapse similar to the `simple_stochastic_synapse` that is provided by PyNN as an extension to nest seems to have been added to NEST recently as a `bernoulli_synapse`. If they are the same, we can drop the `simple_stochastic_synapse` from PyNN (or alias it to the `bernoulli_synapse` to maintain backwards compatibility.

- PR: https://github.com/nest/nest-simulator/pull/747/files
- Source https://github.com/nest/nest-simulator/blob/master/models/bernoulli_connection.h

**Comment by apdavison** [comment]
How similar is "similar"?

It would be great if they are functionally the same.

**Comment by sanjayankur31** [comment]
I'm looking at the two sources now. Should be able to tell in a bit.

**Comment by sanjayankur31** [comment]
They seem to be identical. Both take a probablity as input and check against a random number drawn from the nest RNG to see if the spike should be sent.

- NEST: https://github.com/nest/nest-simulator/blob/master/models/bernoulli_connection.h#L150
- PyNN: https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/nest/extensions/simple_stochastic_connection.h#L158

The NEST version also handles "multiplicity", which the PyNN version does not.

**Comment by apdavison** [comment]
This was implemented in 12a9108fa1b122996c614a26cbbdcdbedcced34a
