### ISSUE TITLE
FromListConnector with empty list fails

### ISSUE THREAD

**Issue by rowleya** [NeuralEnsemble/PyNN#618]
It looks like FromListConnector is designed to work if the user specifies an empty list:
https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/connectors.py#L486

but it also looks like this won't actually work, as n_columns is not then set:
https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/connectors.py#L489

Is this case meant to be handled or should an empty list cause an error?

**Comment by apdavison** [comment]
closed by #619
