### ISSUE TITLE
The units issue of adaptation parameter in AdEx model in PyNN (EIF_cond_alpha_isfa_ista)

### ISSUE THREAD

**Issue by Amenty** [NeuralEnsemble/PyNN#620]
In PyNN 0.9.3 documentation (http://neuralensemble.org/docs/PyNN/reference/neuronmodels.html#pyNN.standardmodels.cells.IF_cond_alpha), in the EIF_cond_alpha_isfa_ista parameters, the units of adaptation a is [uS], and the default parameter is 4. In the PyNN 0.9.3 source code, it is 4 [nS]. In the older PyNN documentation (0.7) it is also 4 [nS]. In (Brette, Gerstner. 2005) it is also 4 [nS]. Could you please confirm that PyNN is using indeed [nS] for adaptation, not [uS], and could you please make corrections in the PyNN 0.9.3 documentations if so? 

Also, I would highly appreciate if you would let me know if there was a change in adaptation units in previous PyNN versions from [nS] to [uS], as this will help me to understand the historical usage of 0.004, and possibly later added *1000 value in the model I am improving.  

Thank you in advance for clarification.

**Comment by apdavison** [comment]
I don't see where in the documentation the units of `a` are given as uS? [Here](http://neuralensemble.org/docs/PyNN/reference/neuronmodels.html#pyNN.standardmodels.cells.EIF_cond_alpha_isfa_ista.units) it gives nS.

(The reason for the factor of 1000 is probably that the normal unit for conductances in PyNN is µS. For some reason, nS was used for the EIF_cond_* models, but was perhaps used inconsistently across the code base. Everything should now be consistent, and nS should be used everywhere for this model).

**Comment by Amenty** [comment]
Yes, just double-checked, it is actually in nS. This is of great help, thank you very much!

**Comment by apdavison** [comment]
The 'a' parameter in the Izhikevich model is not related to the 'a' parameter in the AdEx model. The units of 'a' in Izhikevich in PyNN are ms<sup>-1</sup>

**Comment by Amenty** [comment]
![Screenshot from 2019-03-14 16-40-44](https://user-images.githubusercontent.com/22543630/54374942-0bd46700-4678-11e9-9b41-19b9972c2884.png)

**Comment by Amenty** [comment]
I think I have the answers now, as I looked into the PyNN source code

**Comment by apdavison** [comment]
ok, great. As I said earlier, it was a historical accident that we used different units for the conductances and for the adaptation parameters; sorry for the confusion!

**Comment by Amenty** [comment]
No worries at all, I am happy that it is all clear now! Thank you for your help and support! I think we can close the thread now.
