### ISSUE TITLE
NEURON 7.6 incompatibility

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/PyNN#623]
Using pyNN version 0.93 (from pypi), and compiled pyNN.neuron mechanisms with NEURON 7.6, I get the following error when importing pyNN.neuron:  

```
In [1]: import pyNN.neuron                                                                                           
Mechanism ProbAMPANMDA_EMS needs to be re-translated.
It's version 6.2.0 "c" code is incompatible with this neuron version.
```

at which point my python interpreter exists.  Is this a known issue with the NEURON mechanisms in pyNN and is there a plan to retranslate them?

**Comment by rgerkin** [comment]
Under a slightly different scenario than the above, from a fresh interpreter:
```
In [1]: import pyNN.neuron                                                                                           
The user defined name, ProbAMPANMDA_EMS, already exists
```
and the interpreter exits.  I can avoid this by commenting out `load_mechanisms(mech_path)` [here](https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/neuron/simulator.py#L551).  I'm not sure what else might have already been loading these mechanisms.

**Comment by rgerkin** [comment]
I think the first of the two issues may be from before recompilation, and the second is from after.  If I try to recompile again:  
```
rick ~/miniconda3/lib/python3.7/site-packages/pyNN/neuron/nmodl $ rm -rf x86_64/
rick ~/miniconda3/lib/python3.7/site-packages/pyNN/neuron/nmodl $ /Applications/NEURON-7.6/nrn/x86_64/bin/nrnivmodl
...
Successfully created x86_64/special
rick ~/miniconda3/lib/python3.7/site-packages/pyNN/neuron/nmodl $ python -c "import pyNN.neuron"
The user defined name, ProbAMPANMDA_EMS, already exists
```

with that message terminating a Python interpreter session.  I don't know if there is a way to make that error be handled more gracefully by NEURON (as a warning followed by redefining the mechanism, or ignoring it, rather than killing the process), but maybe @ramcdougal can comment.  

FYI, this is in OSX, so it could be one of the various OSX toolchain pathologies, but I have been running NEURON 7.6 through miniconda Python 3.7 on OSX successfully in other applications.

**Comment by ramcdougal** [comment]
Does the "already exists" error go away if you run from a different directory?

What I think is happening is that PyNN is importing NEURON which always loads the mechanisms that are in the current directory... and then when it tries to explicitly import the PyNN mechanisms, well of course they're already defined because its literally the same files.

**Comment by rgerkin** [comment]
I'm not at that computer to check, but this is so likely to be correct that I am going to close this issue and will only reopen if this doesn't resolve it.
