### ISSUE TITLE
Inconsistent behaviour of inhibitory receptor_type/negative weight signs

### ISSUE THREAD

**Issue by costrau** [NeuralEnsemble/PyNN#625]
Hello,

there are already a few reports on a similar issue (e.g. #597), but nevertheless it seems this is not solved yet. It seems that creating inhibitory connections is implemented quite different between neuron models and simulators...
On NEST (2.14) I observed (I&F models):
- conductance based model: if all weights are positive, you can choose the receptor_type to be inhibitory or excitatory to achieve the wanted behaviour. An alternative is too leave receptor_type as default and use negative weights. (By the way, negative weight and receptor_type="inhibitory" acts excitatory)
- current based model: choosing the receptor_type has no effect.

This so far would not be a big problem. As a user you can just leave the receptor_type aside, and use negative weights for inhibitory connections.
However, the SpiNNaker software stack just ignores the sign of the weights, and only relies on the receptor_type. This is also true for FromList Connections, which then need to be separated.

All in all, it would be nice if different neuron types and backends would behave in the same way, so either ignoring the receptor_type flag or ignoring the sign of the weight. 

Thanks in advance and I am happy to discuss this issue/provide some example scripts if necessary.

**Comment by pedroernesto** [comment]
Maybe pertinent to this discussion, just to mention another example to specify the type of synaptic connections: by the relative position of the reversal excitatory/inhibitory potentials respect to the threshold value, no signs are needed. For instance, this paper:
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0175135

**Comment by apdavison** [comment]
Thanks for pointing this out. There is a function which checks that weights are valid - see https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/standardmodels/__init__.py#L246 but for some reason the place where this function is called is commented out.

The expected behaviour is:
- for conductance-based synapses, weights must always be positive. Putting negative weights should raise an Exception. If you need an inhibitory effect, you need to choose receptor_type="inhibitory" (it then uses the e_rev_inh for the reversal potential, so you need to ensure the value of this parameter is below the resting potential)
- for current-based synapses, weights must be positive for "excitatory" and negative for "inhibitory". Anything else should raise an Exception.

**Comment by costrau** [comment]
Thank you for the quick answer. Can you explain, why the expected behaviour differs for different neuron types?
I actually do not understand why the Projection interface depends on the neuron type it is connecting to. These seem to be two independent things (from a very high level view).

**Comment by apdavison** [comment]
From a physical point of view, a negative current has a clearly understood meaning; a negative conductance less so. I agree it might be simpler to say that all weights must be positive and their effect depends on the receptor type, but this would be a major backwards-compatibility-breaking change.

A Projection represents both an axon and a synapse. The synapse has both a pre- and post-synaptic part, it therefore depends in principle both on the pre- and post-synaptic neuron types.

**Comment by costrau** [comment]
I see your point, and personally, I can live with raising an exception in every faulty case. However, I would propose to expand the documentation of the Projection, which currently says something like

> For standard cells, this can be ‘excitatory’ or ‘inhibitory’

and suggests, that IF_curr_exp is not a "standard cell". Furthermore, the documentation of the different synapse types should at least mention that the sign of the weight might have different meaning depending on the cell types and the receptor_type of the projection.

At last, the FromFile, FromList and Array connectors (I have not checked how these behave at the moment) should also give a hint in the documentation and raise an exception: For your proposed behaviour, a list of mixed connections (excitatory and inhibitory) msut be separated in case of conductance based models.

**Comment by apdavison** [comment]
> a list of mixed connections (excitatory and inhibitory) must be separated in case of conductance based models.

Yes, this is true in all cases, both for conductance and current-based.

**Comment by costrau** [comment]
Thanks for the clarification and the discussion!

**Comment by apdavison** [comment]
Weight checks restored, and documentation improved in dfc62cb58a39a32a961095b66905bea754066200

(note that the documentation changes will not be visible in the built documentation until the next release).
