### ISSUE TITLE
Add ability to apply current pulse to cells in Sonata network

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#627]
Currently only spikes supported: https://github.com/NeuralEnsemble/PyNN/blob/serialization/pyNN/serialization/sonata.py#L1121

Would be useful for tests, see 
https://github.com/pgleeson/sonata/blob/tests/examples/sim_tests/intfire/one_cell_iclamp/input/simulation_config.json#L28
Same format used for Neuron/detailed cells
https://github.com/AllenInstitute/sonata/blob/master/examples/5_cells_iclamp/simulation_config.json#L29

**Comment by apdavison** [comment]
Implemented in a36629c963
