### ISSUE TITLE
Multiple electrodes current plot error in Brian

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#631]
When employing multiple electrodes in a simulation, e.g.:

```
dc_source = DCSource(amplitude=0.5, start=25, stop=50)
ac_source = ACSource(start=75, stop=125, amplitude=0.5, offset=0.25, frequency=100.0, phase=0.0)
noisy_source = NoisyCurrentSource(mean=0.5, stdev=0.05, start=150, stop=175, dt=1.0)
step_source = StepCurrentSource(times=[200, 225, 250], amplitudes=[0.4, 0.6, 0.2])
```

 Brian producing incorrect output for electrode's current plot:
![image](https://user-images.githubusercontent.com/24866517/56589786-35bd6980-65e6-11e9-9db8-1c429d2676ce.png)
(Note: error described in #630 also exists here)

Correct output, as observed for NEURON, would be
![image](https://user-images.githubusercontent.com/24866517/56589820-44a41c00-65e6-11e9-8254-6a1f7b977f21.png)

**Comment by appukuttan-shailesh** [comment]
Error also when two current sources are active over same period, e.g.:
```
dc1_source = DCSource(amplitude=0.5, start=25, stop=50)
dc2_source = DCSource(amplitude=-0.5, start=40, stop=80)
```
![image](https://user-images.githubusercontent.com/24866517/56678871-ff561c00-66c3-11e9-92ec-3a71a0389d35.png)

**Comment by appukuttan-shailesh** [comment]
Current recording in Brian is achieved by recording the `i_inj` parameter of the neuron's equation. The problem that arises here is that all the currents being injected into the cell is summed on this same parameter. Hence, there doesn't appear to exist any recordable parameter by which we can record individual currents.

`ACSource` and `NoisyCurrentSource` are computed for every time instant while `DCSource` and `StepCurrentSource` are not. If the latter are altered to have the entire time series data, and all the calculated values are recorded explicitly within `pyNN.brian` then we could potentially resolve this.

@apdavison : Your thoughts on this problem? Let me know if you can think of a neater workaround.

**Comment by apdavison** [comment]
I suggest recording explicitly for `NoisyCurrentSource` and `ACSource`, and for the others generating the "recorded" data on the fly when `get_data()` is called.
