### ISSUE TITLE
ACSource has different behaviour in NEST 2.12.0

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/PyNN#643]
https://github.com/OpenSourceBrain/PyNNShowcase/blob/e279663c4e90181313c4f85dca941fde3364fed2/PyNN/InputsTest.py#L35-L36

In the example above there is a different phase to the AC current injected into the cell for NEST (middle below) as compared to Neuron (top) and Brian (bottom)

![Selection_999(124)](https://user-images.githubusercontent.com/1556687/59348210-772ce400-8d0e-11e9-823a-7f535a238150.png)

Reproduce with:

    python InputsTest.py neuron -gui
    python InputsTest.py nest -gui
    python InputsTest.py brian -gui

May be related to https://github.com/NeuralEnsemble/PyNN/issues/443, but more likely due to setting of phase of sine wave.

**Comment by appukuttan-shailesh** [comment]
I get similar response across all simulators:
![image](https://user-images.githubusercontent.com/24866517/59500686-3c57b700-8e9a-11e9-801b-4229cf579359.png)

I am using the PyNN==0.9.4 (pip install) with PyNEST==2.14.0. 
@pgleeson : Could you re-check this?

**Comment by pgleeson** [comment]
I was checking with NEST 2.12.0. I've checked with v2.16.0 and the behaviour is the same as Neuron/Brian, so it's only an issue with 2.12. 

Have updated the title of the issue to reflect this... Thanks for checking @appukuttan-shailesh
