### ISSUE TITLE
Question: Change spiking behavior of a population of type SpikeSourceArray

### ISSUE THREAD

**Issue by aWeinzierl** [NeuralEnsemble/PyNN#644]
Is it possible to adapt the spiking behavior after the population has been created/after some simulation progress?

In other words, is it possible to change the neuron type of a population (this way I could just replace the SpikeSourceArray type by a SpikeSourceArray type with different spiking behavior) or update the associated array of SpikeSourceArray?

My goal is (1) to adapt the spiking behavior according to a custom input and (2) deal with unknown input.

**Comment by apdavison** [comment]
Hi, the answer is yes. You can't change the neuron type of a population, but at any time in a simulation, you can set the "spike_times" parameter of a SpikeSourceArray population.

I've just added a new example demonstrating this [here](https://github.com/NeuralEnsemble/PyNN/blob/master/examples/update_spike_source_array.py)

(Note that if you are using the NEURON backend you will need to update to the latest version of PyNN in the master branch, as writing the example uncovered a bug in pyNN.neuron. If using NEST or Brian, the latest PyNN release should work)

**Comment by aWeinzierl** [comment]
Awesome, thanks a lot! 
I successfully applied it.

> but at any time in a simulation, you can set the "spike_times" parameter of a SpikeSourceArray population

This includes callbacks and when the simulation is stopped (after `run()` or `run_until()`). 
I wonder if it is *legal* to modify the parameters during `run()` or `run_until()`, too, without using callbacks.

**Comment by apdavison** [comment]
Unfortunately no interaction with the simulator is possible during `run()`. The approach is therefore to split a simulation into multiple stages, and make changes between `run()` calls. Callbacks are just a way to simplify this.

It would be possible to develop a new, adaptive spike source model, but this would need to be implemented separately for NEURON, NEST, etc., it cannot be implemented purely at the PyNN level.
