### ISSUE TITLE
SpikeSourcePoisson: Crash on rate change and rate adaption lag

### ISSUE THREAD

**Issue by aWeinzierl** [NeuralEnsemble/PyNN#650]
I have noticed that NEST throws an error, when the rate of a `SpikeSourcePoisson` is updated from any positive value to 0  and to any positive value again.
In other words, once the rate is set to zero, it cannot be changed anymore. It seems like this issue is independant of the temporal location.

The exception thrown is the following:
> python2.7: /pathToNestSimulator/nest-simulator-2.16.0/nestkernel/event_delivery_manager.h:564: nest::delay nest::EventDeliveryManager::get_slice_modulo(nest::delay): Assertion `static_cast< std::vector< delay >::size_type >( d ) < slice_moduli_.size()' failed.

Further, any rate change of a specific neuron is not applied before the **next spike at the previous rate**. This is problematic when dealing with low rates as spikes occur only rarely.
For instance, with a rate of 1 it is not unlikely that there is not a spike for a few seconds.
As a result, a rate change can and will be applied extremely delayed.

**Comment by apdavison** [comment]
These seem to be NEST behaviours that PyNN can't do much about. Perhaps for the first issue we could set the rate to a very-small-but-not-zero rate to avoid the exception, for the second, probably the best we can do is document the behaviour and perhaps give a warning.

Please could you ask about these issues on the NEST mailing list? The first problem is probably a bug they could fix, and there may be a workaround for the second problem.

**Comment by apdavison** [comment]
The problems have been fixed in NEST, and should appear in the NEST 2.18.1 release.
