### ISSUE TITLE
Problem setting refractory period/ reset value  in brian

### ISSUE THREAD

**Issue by AndreiMoise111** [NeuralEnsemble/PyNN#651]
Hello, 
So I have found a bug, if you want to modify the refractory period it modifies it to 0.

this is my script:
![brian1bug_screenshot](https://user-images.githubusercontent.com/47896735/64160634-8ec2c700-ce3c-11e9-929a-5fcc2bc00ef5.png)

this is what I get :
![brian1bug_plotresults](https://user-images.githubusercontent.com/47896735/64160832-ed884080-ce3c-11e9-9967-21ad6d20c8d5.png)

this is what it should have plotted: 
![brian1bug_brian2results](https://user-images.githubusercontent.com/47896735/64161060-448e1580-ce3d-11e9-9f96-63cc483f506b.png)

**Comment by apdavison** [comment]
Transcription of screenshot:
```python
import sys
from pyNN.utility import get_script_args, get_simulator
import matplotlib.pyplot as plt
from pyNN.space import *

simulator_name = get_script_args(1)[0]
exec("from pyNN.%s import *" % simulator_name)

setup(min_delay=0.1)

cells = Population(5, IF_curr_exp(v_rest=-65, v_thresh=-55, tau_refrac=30, i_offset=-1.0))
cells1 = Population(5, IF_curr_exp(v_rest=-65, v_thresh=-55, tau_refrac=10, i_offset=-1.0))

cells1.set(tau_refrac=30.0)

dc_source = DCSource(amplitude=4, start=25, stop=50)
dc_source1 = DCSource(amplitude=4, start=25, stop=50)
cells[0].inject(dc_source)
cells1[0].inject(dc_source1)
cells.record(["v"])
cells1.record(["v"])

run(100)

plt.subplot(2, 2, 1)
vm = cells.get_data().segments[0].filter(name="v")[0]
plt.plot(vm.times, vm[:, 0], "r")
plt.xlabel("time (ms)")
plt.ylabel("Vm (mV)")

plt.subplot(2, 2, 2)
vm = cells.get_data().segments[0].filter(name="v")[0]
plt.plot(vm.times, vm[:, 0], "r")
plt.xlabel("time (ms)")
plt.ylabel("Vm (mV)")

plt.show(block=True)
end()
```

**Comment by apdavison** [comment]
This appears to have been fixed at some point. pyNN.brian2 generates the second set of plots.
