### ISSUE TITLE
Network.populations is empty after import_from_sonata() 

### ISSUE THREAD

**Issue by stefanonardo** [NeuralEnsemble/PyNN#658]
Assuming that
sonata population == pynn assembly and
sonata node group == pynn population,
it would be useful to have a reference to the node groups in the Network object, i.e. the array 'populations' should be populated inside the `to_population()` method. 
This would be helpful to make Sonata compatible with applications written for pynn networks. For instance, this is essential in HBP NRP, since we are also interested in homogeneous groups of neurons and we cannot rely on assemblies.

If you agree, I can create a PR.

**Comment by apdavison** [comment]
I see the problem: if assemblies are added in the Network constructor, then the constituent populations are added to `network.populations`, but if the assemblies are added directly to `network.assemblies`, this doesn't happen.

I would be very happy to receive a PR that fixes this - many thanks for the offer.

**Comment by stefanonardo** [comment]
I didn't notice there was a `get_component(label)` method already, this would solve the problem of finding the populations inside a Network composed of assemblies only. 
I'm not even sure now if my proposal is correct. Maybe `Network.populations` should only contains those populations that are added in a "stand-alone" way? I don't know what is the semantic of `Network.assemblies` and `Network.populations`, but adding a population that it is inside an assembly to `Network.populations` could be redundant, or convenient, depending on the case.
