### ISSUE TITLE
IF_cond_alpha documentation doesn't match the code parameter values

### ISSUE THREAD

**Issue by andrewgait** [NeuralEnsemble/PyNN#665]
http://neuralensemble.org/docs/PyNN/standardmodels.html has different parameter values for IF_cond_alpha than the code in https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/standardmodels/cells.py - I'm assuming the values in the code are correct?

**Comment by apdavison** [comment]
Yes, indeed, many thanks for spotting that. I've fixed it in the master branch, the online docs will be automatically updated at the next release.
