### ISSUE TITLE
Add CI for Windows

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/PyNN#679]
An increasing number of people are trying to use PyNN on Windows, so we should add continuous integration testing for that platform, e.g. using Appveyor or CircleCI

**Comment by mstimberg** [comment]
I have experience in setting up Windows testing under Appveyor and Azure Pipelines, so I could help with this if needed. Azure pipelines has the advantage that it runs different test configurations in parallel whereas Appveyor runs them all sequentially.

**Comment by apdavison** [comment]
Thanks @mstimberg. Which is the quickest/easiest to configure, in your experience?

**Comment by mstimberg** [comment]
I don't think there's a fundamental difference between the two for setting them up. Appveyor is maybe a bit more similar to travis which could be helpful.

**Comment by apdavison** [comment]
ended up using Github Actions for this, although we don't yet have testing of the NEURON backend on Windows.
