### ISSUE TITLE
lack of _version.py 

### ISSUE THREAD

**Issue by alan-stokes** [NeuralEnsemble/PyNN#680]
We were trying to find a way to figure out what version of pynn a user was using, and we thought wed find _version.py file at the top of the pynn install, coz that's just good practice. alas not. 

Please fix in future releases.

**Comment by mstimberg** [comment]
> We were trying to find a way to figure out what version of pynn a user was using, and we thought wed find _version.py file at the top of the pynn install, coz that's just good practice. alas not.

I am not a PyNN developer, but I have to say that I don't consider the lack of `_version.py` bad practice. Having a file storing the version is just one of the many options given in the (more or less) [authoritative source on packaging](https://packaging.python.org/guides/single-sourcing-package-version/), and naming this file `_version.py` is certainly not the only possibility.

Why not import `pyNN` and check `pyNN.__version__`? This is the canonical way for checking a package version, isn't it?

**Comment by apdavison** [comment]
```
import pyNN

print(pyNN.__version__)
```
