### ISSUE TITLE
ModuleNotFoundError: No module named 'example_1_pyloric_net_plot'

### ISSUE THREAD

**Issue by ramapati166** [NeuralEnsemble/PyNN#681]
In "Brian 2, an intuitive and efficient neural simulator" a numbers of case studies have been done and also its codes are available in GitHub, but when I start simulating with same simulation code using Brian2 simulator it is showing following error message. If anyone can help me how I can run the simulation code for the "case study I" in the above mentioned paper I will be highly obliged to you. Thanks in advance. 

**ModuleN**otFoundError                       Traceback (most recent call last)
<ipython-input-2-610cdbb96f99> in <module>
     92 device.build(directory='example_1')
     93 spike_trains = spikes.spike_trains()
---> 94 from example_1_pyloric_net_plot import do_pyloric_net_plot
     95 do_pyloric_net_plot(spike_trains, M.t, M.v, 'v',
     96                     init_time, observe_time, adapt_time);

ModuleNotFoundError: No module named 'example_1_pyloric_net_plot'

**Comment by appukuttan-shailesh** [comment]
The Brian2 backend for PyNN is still in development phase (PyNN supports Brian(1) but not yet Brian2).

Also, I believe this query should be posted in the Brian2 github issue tracker:
https://github.com/brian-team/brian2/issues
as "case study I" that you have referred to with Brian2 code, and not PyNN.

**Comment by mstimberg** [comment]
Hi, as @appukuttan-shailesh  said, this is the issue tracker for the PyNN simulation interface, not for the Brian 2 simulator. You can use the issue tracker he linked, but a better place to ask this kind of questions would probably be the [Brian forum](https://brian.discourse.group).
Regarding your actual issue: the jupyter notebook for the first case study needs the Python file `example_1_pyloric_net_plot.py` for the plotting code. If you downloaded the jupyter notebook on your machine, you need to also download that file and place it in the same directory as your notebook (or you could clone/download the whole repository with all the files). Alternatively, you can run the notebook [online on the binder infrastructure](https://mybinder.org/v2/gh/brian-team/brian2_paper_examples/master?filepath=example_1_pyloric_network.ipynb), this has access to all the necessary files.

**Comment by ramapati166** [comment]
Thanks a lot..
