### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 

### ISSUE THREAD

**Issue by osmandamfodum** [NeuralEnsemble/PyNN#683]
I got this error any have an answer?

**Comment by apdavison** [comment]
Hi @osmandamfodum, I need more information to answer this question. Please could you post the full traceback for the error?

**Comment by osmandamfodum** [comment]
Traceback (most recent call last):
  File "C:/Users/DAMFODUM/OneDrive/Desktop/set/python3 main.py.py", line 5, in <module>
    class MedicalExpert(KnowledgeEngine):
  File "C:/Users/DAMFODUM/OneDrive/Desktop/set/python3 main.py.py", line 18, in MedicalExpert
    @Rule(Fact(findDisease='true'), NOT(Fact(name=W()), salience=1000))
TypeError: __new__() got an unexpected keyword argument 'salience'

**Comment by osmandamfodum** [comment]
> 
![Screenshot (14)](https://user-images.githubusercontent.com/68653173/97802145-11663280-1c4a-11eb-9f8e-e8f3921edd44.png)

**Comment by apdavison** [comment]
This doesn't appear to have anything to do with PyNN. Based on the code sample, you should perhaps ask your question here: https://github.com/nilp0inter/experta
