### ISSUE TITLE
plotting still uses channel_index

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/PyNN#708]
According to 
https://neo.readthedocs.io/en/stable/releases/0.9.0.html
We should no longer be using channel_index.

Yes https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/utility/plotting.py
Still references channel_index

**Comment by jiegec** [comment]
Neo 0.10.0 is release and ChannelIndex is removed. A fix is needed for neo 0.10.0 support. @apdavison

**Comment by apdavison** [comment]
most of the changes related to the removal of ChannelIndex from Neo were in #732. plotting.py was fixed in bbf0e206.

**Comment by Christian-B** [comment]
regrettably the master version of
plotting.py still uses channel_index index

for example:
for i in signal_array.array_annotations["channel_index"].argsort():

See https://github.com/NeuralEnsemble/PyNN/blob/435adeda83e4b082a61acbb24953263aca52837f/pyNN/utility/plotting.py#L80

**Comment by apdavison** [comment]
Note that you will still find reference to "channel_index", but this is now just an array annotation added by PyNN [here](https://github.com/NeuralEnsemble/PyNN/blob/00a67992285431ad09ad325fcec0020bbe28acdd/pyNN/recording/__init__.py#L311) to facilitate plotting/data analysis.

**Comment by Christian-B** [comment]
Thank you. My recent comment have been deleted as they where not correct. Apologies.
