### ISSUE TITLE
Warning with NumPy. 

### ISSUE THREAD

**Issue by cxr001** [NeuralEnsemble/PyNN#717]
I don't know the spicific code I used, I just see this warning, and it seems because of the updating of NumPy and is in "recording.py" line 115

\pyNN\neuron\recording.py:115: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  signals = numpy.vstack((id._cell.traces[variable] for id in ids)).T

**Comment by apdavison** [comment]
thanks. The problem in recording.py was fixed in an unrelated pull request, I've just made a commit to remove another place in the code where this warning was generated.
