### ISSUE TITLE
How to install PyNN on Windows

### ISSUE THREAD

**Issue by appukuttan-shailesh** [NeuralEnsemble/PyNN#729]
I have been trying to install PyNN on Windows (without using VMware, VirtualBox or WSL) but not succeeding. The conda version of PyNN is pretty outdated (v0.7.5) so that doesn't seem to be an option. When I try installing via `pip` under conda, it keeps getting stuck at 
> Building wheel for pyNN (setup.py) ...

![image](https://user-images.githubusercontent.com/24866517/137454443-16f97354-ba53-4e88-9441-160b039ffff2.png)

I was curious if we had any Windows-based PyNN users out here. If yes, can anyone describe how you setup PyNN on your systems. Thanks.

Tagging @cxr001, @ChihweiLHBird, @ashwin4ever,  @tollybe, @rowleya as you all seem to have some experience on setting up PyNN on Windows (based on your posts/comments in past PyNN Windows issues).

**Comment by cxr001** [comment]
pip wheel    
on your cmd

**Comment by apdavison** [comment]
@appukuttan-shailesh could you try again with the latest version of PyNN?

**Comment by appukuttan-shailesh** [comment]
@apdavison : It works with PyNN v0.10.0 without any additional steps.

![image](https://user-images.githubusercontent.com/24866517/165093528-301637fd-9dcd-4a9f-8aad-cdb98f421abf.png)

Closing this ticket. Thanks @ChihweiLHBird , @cxr001 for your inputs in debugging this.
