### ISSUE TITLE
compiled mod file is not callable in python

### ISSUE THREAD

**Issue by Sean535** [NeuralEnsemble/PyNN#733]
h.ExpISyn, h.AlphaISyn and h.AlphaSyn are not callable, while calling h.ExpSyn is fine
AttributeError: 'hoc.HocObject' object has no attribute h.ExpISyn
AttributeError: 'hoc.HocObject' object has no attribute h.AlphaISyn
AttributeError: 'hoc.HocObject' object has no attribute h.AlphaSyn

the mod files in:
~\anaconda3\Lib\site-packages\pyNN\neuron\nmodl
~\anaconda3\Lib\site-packages\pyNN\neuron\nmodl\AMD64.libs\libnrnmech.so
~\anaconda3\Lib\site-packages\pyNN\neuron\nmodl\x86_64.libs\libnrnmech.so
has already been compiled either by mknrndll or nrnivmodl

environment:
Win10 (20H2)
python 3.8
pynn 0.9.6
neuron 8

**Comment by apdavison** [comment]
Please could you try again with the latest version of PyNN? We've fixed a few problems when using PyNN with NEURON v8.

**Comment by apdavison** [comment]
I've tested this with Windows 11, Python 3.10, NEURON 8.2 and the current PyNN master branch, and h.ExpISyn, h.AlphaISyn and h.AlphaSyn are all available.

Please comment if you're still encountering problems, and I'll reopen the ticket.
