### ISSUE TITLE
problem running pynn and nest

### ISSUE THREAD

**Issue by ChrisHuyck** [NeuralEnsemble/PyNN#736]
A student of mine is installing pyNN and Nest in an ubuntu 20.04 virtual box.
Following directions from http://neuralensemble.org/docs/PyNN/installation.html
he first installs Nest.  That installs nest 3.1 and if you run nest from the command line you get the SLI prompt.
He then uses
 pip install pyNN
which gives him version 0.9.6

from python (python3.8)
he can import pyNN, but
import pyNN.nest # or pyNN.nest as sim
gives him an error 
which seems to come from importing simulator.py
off_grid_spiking is a readonly kernel parameter.

**Comment by apdavison** [comment]
PyNN 0.10.0 has now been released, with support for NEST 3.1

PyNN 0.10.1 will be released very soon, with support for the current latest version of NEST, v3.3.

I'll close this ticket now, please let us know if you have further problems installing PyNN with NEST.
