### ISSUE TITLE
http://neuralensemble.org is down

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/PyNN#745]
Are you aware the doc site http://neuralensemble.org/ is still down

**Comment by Christian-B** [comment]
This appears to be hosted on facets-vm3.kip.uni-heidelberg.de 

i have emailed Bjoern

**Comment by Christian-B** [comment]
Reply from Bjoern

"Yes, I am aware of the problem with the web-service and I sent mail to Andrew Davison."

**Comment by apdavison** [comment]
Hi Christian, yes, we have a monitoring tool which checks the site is up. Due to a family emergency I have not been able to deal with this yet, the site should be back up later today.
