### ISSUE TITLE
no structure_default.txt

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/PyNN#768]
class BaseStructure.describe has template='structure_default.txt'
https://github.com/NeuralEnsemble/PyNN/blob/8d22cef457779eed6d70e6de5a4990e11f384400/pyNN/space.py#L164

Yet https://github.com/NeuralEnsemble/PyNN/tree/master/pyNN/descriptions/templates/string
has no structure_default.txt file.

Nor do any of the other directories.

**Comment by apdavison** [comment]
this should be fixed in #770
