### ISSUE TITLE
Population describe String template broken.

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/PyNN#769]
The template for population
https://github.com/NeuralEnsemble/PyNN/blob/master/pyNN/descriptions/templates/string/projection_default.txt

has the line:
Cell type   : $celltype.name

yet is the Scelltype returns a dict with a name value as expected.
The result is:

Cell type   : {'name': 'IF_curr_exp'}.name

and not the expected

Cell type   : 'IF_curr_exp'

**Comment by apdavison** [comment]
this should be fixed in #770
