### ISSUE TITLE
Value error when executing stdp code

### ISSUE THREAD

**Issue by hanbuck30** [NeuralEnsemble/PyNN#803]
I ran stdp_network.py from the examples, but a ValueError occurred. The simulator is Brian2, and the error was:
ValueError: The pyNN.brian2 backend does not currently support dendritic delays: for the purpose of STDP calculations all delays are assumed to be axonal.
How can I solve this?

**Comment by apdavison** [comment]
In the `stdp_network.py` script, add `dendritic_delay_fraction=0` to the `STDPMechanism` constructor after line 54.
