### ISSUE TITLE
negative weights do not cause IPSPs in IF_cond_alpha with pyNN.neuron

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/PyNN#86]
Connecting a SpikeSource with an IF_cond_alpha neuron and specifying a negative weight results in EPSPs instead of IPSPs.

Sample code attached.

---
### Imported from Trac ticket:95

**Opened**: 2008-06-05 12:04:46
**Last modified**: 2008-06-05 14:38:53
**Component**: oldneuron
**Priority**: major
**Owner**: apdavison
**Reporter**: mschmucker

**Comment by ruthvik92** [comment]
So, If i use `Projections`, in order to have an inhibitory synapse, I should have -ve weights AND `target = inhibitory` rite?

**Comment by apdavison** [comment]
For conductance-based synapses: `target='inhibitory'` and +ve weights
For current-based synapses: `target='inhibitory'` and -ve weights
